# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Generated by Merlin Studio. Run 2-project-factory against this dataset.
# Copy this directory into the stage as datasets/data-platform-stg/, then apply with these variables.

stage_name = "data-platform-stg"

factories_config = {
  dataset = "datasets/data-platform-stg"
}
