# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# DEPARTMENT-seller/core -- the "Seller Platform" department (seller), once.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# A department is an increment on the landing zone that exists, not a
# regeneration of it. This root creates what the department has once: a folder
# under every environment folder, a core project holding the deploy identities
# and the state bucket, and a key ring in the central key project. Nothing the
# landing zone's state owns is modified; every value naming something that
# exists (a folder, a project) is in terraform.tfvars, confirmed against the
# real organisation by deploy/preflight-seller.sh.

# --- Development: the department's folder under the environment's --------
# Folder order is environment, then department: the environment folder's
# policies and tags reach the department without the department having to
# restate them.
module "folder-dev" {
  source = "../../../../modules/folder"
  parent = var.environment_folders["dev"]
  name   = "Seller Platform"
  iam_by_principals = {
    "group:gcp-seller-owners@vendora.eu" = ["roles/resourcemanager.folderViewer"]
  }
}

# --- Staging: the department's folder under the environment's --------
# Folder order is environment, then department: the environment folder's
# policies and tags reach the department without the department having to
# restate them.
module "folder-stg" {
  source = "../../../../modules/folder"
  parent = var.environment_folders["stg"]
  name   = "Seller Platform"
  iam_by_principals = {
    "group:gcp-seller-owners@vendora.eu" = ["roles/resourcemanager.folderViewer"]
  }
}

# --- Production: the department's folder under the environment's --------
# Folder order is environment, then department: the environment folder's
# policies and tags reach the department without the department having to
# restate them.
module "folder-prd" {
  source = "../../../../modules/folder"
  parent = var.environment_folders["prd"]
  name   = "Seller Platform"
  iam_by_principals = {
    "group:gcp-seller-owners@vendora.eu" = ["roles/resourcemanager.folderViewer"]
  }
}

# --- Core project ----------------------------------------------------------
# Holds what the department has once: its deploy identities and its state.
# It sits under the Shared Services folder beside the landing zone's own
# central project, because it is shared by every environment of the department.
module "project-core" {
  source          = "../../../../modules/project"
  billing_account = var.billing_account
  parent          = var.shared_services_folder
  prefix          = var.prefix
  name            = "seller-core-0"
  services = [
    "cloudkms.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "iam.googleapis.com",
    "serviceusage.googleapis.com",
    "storage.googleapis.com",
  ]
  labels = {
    department  = "seller"
    environment = "shared"
    managed-by  = "merlin"
  }
}

# --- State bucket ----------------------------------------------------------
# One bucket, one prefix per root. The core root's own state moves here after
# the first apply (deploy/apply-seller.sh does the migration), the way
# FAST's bootstrap stage does.
module "bucket-state" {
  source     = "../../../../modules/gcs"
  project_id = module.project-core.project_id
  prefix     = var.prefix
  name       = "seller-iac-state"
  location   = var.primary_region
  versioning = true
  labels = {
    department = "seller"
    managed-by = "merlin"
  }
}

# --- Deploy identity for dev ---------------------------------------
# The environment root of dev grants this account what it needs in
# that environment's projects, so one identity never reaches every environment.
module "sa-iac-dev" {
  source      = "../../../../modules/iam-service-account"
  project_id  = module.project-core.project_id
  name        = "iac-seller-dev"
  description = "Applies the Seller Platform department's dev root and application stages"
  iam_storage_roles = {
    (module.bucket-state.name) = ["roles/storage.objectAdmin"]
  }
}

# --- Deploy identity for stg ---------------------------------------
# The environment root of stg grants this account what it needs in
# that environment's projects, so one identity never reaches every environment.
module "sa-iac-stg" {
  source      = "../../../../modules/iam-service-account"
  project_id  = module.project-core.project_id
  name        = "iac-seller-stg"
  description = "Applies the Seller Platform department's stg root and application stages"
  iam_storage_roles = {
    (module.bucket-state.name) = ["roles/storage.objectAdmin"]
  }
}

# --- Deploy identity for prd ---------------------------------------
# The environment root of prd grants this account what it needs in
# that environment's projects, so one identity never reaches every environment.
module "sa-iac-prd" {
  source      = "../../../../modules/iam-service-account"
  project_id  = module.project-core.project_id
  name        = "iac-seller-prd"
  description = "Applies the Seller Platform department's prd root and application stages"
  iam_storage_roles = {
    (module.bucket-state.name) = ["roles/storage.objectAdmin"]
  }
}

# --- Key ring in the central key project ------------------------------------
# Central by decision: the key project is where the organisation's keys are
# audited and rotated. The department's key is its own; application stages
# create keys of their own beside it.
module "kms" {
  source     = "../../../../modules/kms"
  project_id = var.key_project
  keyring = {
    location = var.primary_region
    name     = "seller-kr-europe-west4"
  }
  keys = {
    "seller-default" = {
      rotation_period = "7776000s"
      labels = {
        department = "seller"
        managed-by = "merlin"
      }
    }
  }
}
