# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# The confirm table, as values. Edit here if the organisation differs from
# what the table showed; the preflight checks every line. The billing account
# and the folders are the exception: their real values live in
# deploy/seller.facts.env, and deploy/apply-seller.sh passes them over these.
prefix                 = "vd"
primary_region         = "europe-west4"
billing_account        = "FAKE00-356D6C-FD4FEF"
shared_services_folder = "folders/000000000001"
key_project            = "vd-sec-core-0"
environment_folders = {
  dev = "folders/000000000101"
  stg = "folders/000000000102"
  prd = "folders/000000000103"
}
