# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# DEPARTMENT-seller/stg -- the "Seller Platform" department in stg.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Applied after DEPARTMENT-seller/core, which created the folder this root
# builds under and the identity that applies it. Everything here is additive:
# a subnet in the environment's existing network, projects under the
# department's own folder, IAM members on the subnet, a firewall policy on the
# department's folder. The landing zone's own resources are read by
# name and never changed.

locals {
  folder_id       = var.department_folder_ids["stg"]
  network         = "projects/${var.network_project}/global/networks/${var.vpc}"
  deploy_identity = var.deploy_service_accounts["stg"]
  # The application stages of this department look their projects up here.
  department_project_ids = {
    "seller-app-stg-0" = module.project-app.project_id
    "seller-dp-stg-0" = module.project-dp.project_id
  }
}

# --- Subnet in vpc-shared-dev ----------------------------------------------
# The department's own address space in the environment's network, so its
# workloads are a range a firewall rule can name. Created in the network's
# host project, beside the landing zone's subnets and owned by this state.
resource "google_compute_subnetwork" "department" {
  project                  = var.network_project
  name                     = "sb-seller-stg-europe-west4"
  region                   = var.primary_region
  network                  = local.network
  ip_cidr_range            = var.subnet_cidr
  private_ip_google_access = true
  log_config {
    aggregation_interval = "INTERVAL_5_SEC"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}

# --- Project seller-app-stg-0 ------------------------------------------------------
# Where the department's services run.
module "project-app" {
  source          = "../../../../modules/project"
  billing_account = var.billing_account
  parent          = local.folder_id
  prefix          = var.prefix
  name            = "seller-app-stg-0"
  services = [
    "compute.googleapis.com",
    "iam.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "run.googleapis.com",
    "secretmanager.googleapis.com",
  ]
  labels = {
    department  = "seller"
    environment = "stg"
    managed-by  = "merlin"
  }
  # A service project of the environment's Shared VPC, like the landing
  # zone's own; which subnet it may use is granted below, on the subnet.
  shared_vpc_service_config = {
    host_project = var.network_project
  }
  iam_by_principals = {
    # The deploy identity applies this department's application stages here.
    "serviceAccount:${local.deploy_identity}" = ["roles/owner"]
    "group:gcp-seller-developers@vendora.eu" = [
      "roles/run.developer",
      "roles/logging.viewer",
      "roles/monitoring.viewer",
    ]
    "group:gcp-seller-qa@vendora.eu" = [
      "roles/viewer",
      "roles/logging.viewer",
    ]
    "group:gcp-seller-owners@vendora.eu" = [
      "roles/editor",
      "roles/iam.securityReviewer",
    ]
  }
}

# --- Project seller-dp-stg-0 ------------------------------------------------------
# Where the department's data lives.
module "project-dp" {
  source          = "../../../../modules/project"
  billing_account = var.billing_account
  parent          = local.folder_id
  prefix          = var.prefix
  name            = "seller-dp-stg-0"
  services = [
    "bigquery.googleapis.com",
    "compute.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "pubsub.googleapis.com",
    "servicenetworking.googleapis.com",
    "sqladmin.googleapis.com",
    "storage.googleapis.com",
  ]
  labels = {
    department  = "seller"
    environment = "stg"
    managed-by  = "merlin"
  }
  # A service project of the environment's Shared VPC, like the landing
  # zone's own; which subnet it may use is granted below, on the subnet.
  shared_vpc_service_config = {
    host_project = var.network_project
  }
  iam_by_principals = {
    # The deploy identity applies this department's application stages here.
    "serviceAccount:${local.deploy_identity}" = ["roles/owner"]
    "group:gcp-seller-developers@vendora.eu" = [
      "roles/bigquery.dataEditor",
      "roles/cloudsql.client",
      "roles/logging.viewer",
    ]
    "group:gcp-seller-qa@vendora.eu" = [
      "roles/viewer",
      "roles/bigquery.dataViewer",
    ]
    "group:gcp-seller-owners@vendora.eu" = [
      "roles/editor",
      "roles/iam.securityReviewer",
    ]
  }
}

# --- Who may use the subnet ------------------------------------------------
# Granted on the subnet, not the host project: the department's projects reach
# their own range and nothing else in the network.
resource "google_compute_subnetwork_iam_member" "app-cloudservices" {
  project    = var.network_project
  region     = var.primary_region
  subnetwork = google_compute_subnetwork.department.name
  role       = "roles/compute.networkUser"
  member     = "serviceAccount:${module.project-app.number}@cloudservices.gserviceaccount.com"
}

resource "google_compute_subnetwork_iam_member" "app-cloud-run" {
  project    = var.network_project
  region     = var.primary_region
  subnetwork = google_compute_subnetwork.department.name
  role       = "roles/compute.networkUser"
  member     = "serviceAccount:service-${module.project-app.number}@serverless-robot-prod.iam.gserviceaccount.com"
}

resource "google_compute_subnetwork_iam_member" "dp-cloudservices" {
  project    = var.network_project
  region     = var.primary_region
  subnetwork = google_compute_subnetwork.department.name
  role       = "roles/compute.networkUser"
  member     = "serviceAccount:${module.project-dp.number}@cloudservices.gserviceaccount.com"
}

resource "google_compute_subnetwork_iam_member" "deploy-identity" {
  project    = var.network_project
  region     = var.primary_region
  subnetwork = google_compute_subnetwork.department.name
  role       = "roles/compute.networkUser"
  member     = "serviceAccount:${local.deploy_identity}"
}

# --- Firewall policy on the department's folder -------------------------------
# Hierarchical, attached to the department's own folder, so it reaches every
# project of the department in this environment and no project outside it.
# It allows what the department needs; whatever the landing zone's policies
# deny above it stays denied.
module "firewall-policy" {
  source    = "../../../../modules/net-firewall-policy"
  name      = "fwp-seller-stg"
  parent_id = local.folder_id
  attachments = {
    department = local.folder_id
  }
  ingress_rules = {
    allow-department = {
      priority    = 1000
      description = "The department's own range"
      match = {
        source_ranges  = [var.subnet_cidr]
        layer4_configs = [{ protocol = "all" }]
      }
    }
    allow-health-checks = {
      priority    = 1010
      description = "Google's load balancer health checks"
      match = {
        source_ranges  = ["35.191.0.0/16", "130.211.0.0/22"]
        layer4_configs = [{ protocol = "tcp" }]
      }
    }
    allow-iap = {
      priority    = 1020
      description = "SSH and RDP through Identity-Aware Proxy only"
      match = {
        source_ranges  = ["35.235.240.0/20"]
        layer4_configs = [{ protocol = "tcp", ports = ["22", "3389"] }]
      }
    }
  }
}
