# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage DEPARTMENT-seller/stg -- the web application firewall, where the backends are.
#
# The security page defines these policies. A backend service can only use a
# policy in its own project, so each policy is created in every project that
# can host one, under the name the page gave it -- the name every front door
# the application stages generate attaches by. Change the rules on the
# security page and apply this stage; every backend follows.

locals {
  project_seller_app_stg_0 = lookup(local.department_project_ids, "seller-app-stg-0", "${var.prefix}-seller-app-stg-0")
}

# --- compliance-waf-policy in seller-app-stg-0 ---------------------------------
resource "google_compute_security_policy" "project_seller_app_stg_0_compliance_waf_policy" {
  project     = local.project_seller_app_stg_0
  name        = "compliance-waf-policy"
  description = "Web application firewall from the landing zone's security page"
  type        = "CLOUD_ARMOR"

  # Learns the shape of normal traffic and proposes rules when it changes.
  adaptive_protection_config {
    layer_7_ddos_defense_config {
      enable = true
    }
  }

  rule {
    action      = "deny(403)"
    priority    = 1000
    description = "sqli-v33-stable"
    match {
      expr {
        expression = "evaluatePreconfiguredWaf('sqli-v33-stable')"
      }
    }
  }

  rule {
    action      = "deny(403)"
    priority    = 1001
    description = "xss-v33-stable"
    match {
      expr {
        expression = "evaluatePreconfiguredWaf('xss-v33-stable')"
      }
    }
  }

  rule {
    action      = "deny(403)"
    priority    = 1002
    description = "lfi-v33-stable"
    match {
      expr {
        expression = "evaluatePreconfiguredWaf('lfi-v33-stable')"
      }
    }
  }

  rule {
    action      = "deny(403)"
    priority    = 1003
    description = "rce-v33-stable"
    match {
      expr {
        expression = "evaluatePreconfiguredWaf('rce-v33-stable')"
      }
    }
  }

  # Whatever no rule above matched. Cloud Armor requires this rule to exist
  # at the lowest priority.
  rule {
    action      = "allow"
    priority    = 2147483647
    description = "default rule"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
  }
}
