# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-services-stg — application services for the "stg" environment.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Reads the FAST outputs of 0-org-setup (project ids, KMS keys) and
# 2-networking (VPC / subnet self links) and instantiates the Fabric
# cloud-run-v2, cloudsql-instance, firestore, secret-manager, cloud-function-v2
# and compute-vm modules. The YAML files next to this root are the readable
# inventory of the same definitions; edit them together.

locals {
  app_project_id  = lookup(var.project_ids, "app-stg-0", "${var.prefix}-app-stg-0")
  data_project_id = lookup(var.project_ids, "dp-stg-0", "${var.prefix}-dp-stg-0")
}

# --- Cloud Run service: api -------------------------------------
module "run-api" {
  source     = "../../../modules/cloud-run-v2"
  project_id = local.app_project_id
  name       = "api"
  region     = "europe-west4"
  containers = {
    app = {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }
  }
  service_config = {
    ingress = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
    scaling = {
      min_instance_count = 1
      max_instance_count = 50
    }
  }
  revision = {
    vpc_access = {
      network = var.vpc_self_links["vpc-shared-dev"]
      subnet  = var.subnet_self_links["vpc-shared-dev"]["europe-west4/sb-stg-europe-west4"]
      egress  = "PRIVATE_RANGES_ONLY"
    }
  }
  encryption_key      = var.kms_keys["cloudrun-kr-europe-west4"]
  deletion_protection = false
  labels = {
    environment = "stg"
    managed-by  = "merlin"
  }
}

# --- Cloud SQL instance: app-db -------------------------------------
module "sql-app-db" {
  source            = "../../../modules/cloudsql-instance"
  project_id        = local.data_project_id
  name              = "app-db"
  region            = "europe-west4"
  database_version  = "POSTGRES_15"
  tier              = "db-custom-2-7680"
  availability_type = "REGIONAL"
  network_config = {
    connectivity = {
      public_ipv4 = false
      psa_config = {
        private_network = var.vpc_self_links["vpc-shared-dev"]
      }
    }
  }
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = false
    retention_count                = 7
  }
  ssl = {
    mode = "ENCRYPTED_ONLY"
  }
  encryption_key_name           = var.kms_keys["cloudsql-kr-europe-west4"]
  gcp_deletion_protection       = false
  terraform_deletion_protection = false
  labels = {
    environment = "stg"
    managed-by  = "merlin"
  }
}
