# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

output "run_services" {
  description = "Cloud Run service ids and URIs."
  value = {
    "api" = {
      id  = module.run-api.id
      uri = module.run-api.service_uri
    }
  }
}

output "sql_instances" {
  description = "Cloud SQL instance ids and connection names."
  value = {
    "app-db" = {
      id              = module.sql-app-db.id
      connection_name = module.sql-app-db.connection_name
    }
  }
  sensitive = true
}
