# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Operations for seller-assistant in stg.
#
# A stage that creates a service and no way to notice it failing is half a
# deliverable. Every alert below says what to do about it, because an alert
# whose runbook is "someone will know" is noise with a pager attached.
#
# The thresholds are Merlin's opinion, not your policy: they are the starting
# points Google's own SLO guidance recommends. Change them once you know what
# this application is actually for. CONFORMANCE.md records them as opinions.

variable "notification_channels" {
  description = "Channels to notify, from the landing zone's monitoring setup. Empty means the policies are created and notify nobody."
  type        = list(string)
  nullable    = false
  default     = []
}

# --- Objective: seller-assistant-api-stg availability -----------
resource "google_monitoring_slo" "seller-assistant-api-stg-availability" {
  project      = local.project_seller_app_stg_0
  service      = google_monitoring_custom_service.seller-assistant-api-stg.service_id
  slo_id       = "seller-assistant-api-stg-availability"
  display_name = "seller-assistant-api-stg availability"

  goal                = 0.99
  rolling_period_days = 28

  request_based_sli {
    good_total_ratio {
      good_service_filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_count\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"seller-assistant-api-stg\"",
        "metric.label.\"response_code_class\"!=\"5xx\"",
      ])
      total_service_filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_count\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"seller-assistant-api-stg\"",
      ])
    }
  }
}

# --- Objective: seller-assistant-api-stg latency -----------
resource "google_monitoring_slo" "seller-assistant-api-stg-latency" {
  project      = local.project_seller_app_stg_0
  service      = google_monitoring_custom_service.seller-assistant-api-stg.service_id
  slo_id       = "seller-assistant-api-stg-latency"
  display_name = "seller-assistant-api-stg latency"

  goal                = 0.95
  rolling_period_days = 28

  request_based_sli {
    distribution_cut {
      distribution_filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_latencies\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"seller-assistant-api-stg\"",
      ])
      range {
        max = 1000
      }
    }
  }
}

# The service an objective is measured against.
resource "google_monitoring_custom_service" "seller-assistant-api-stg" {
  project      = local.project_seller_app_stg_0
  service_id   = "seller-assistant-api-stg"
  display_name = "seller-assistant-api-stg"
}

# --- Alert: seller-assistant-api-stg errors ------------------
# the service is returning server errors
resource "google_monitoring_alert_policy" "seller-assistant-api-stg-errors" {
  project      = local.project_seller_app_stg_0
  display_name = "seller-assistant-api-stg: the service is returning server errors"
  combiner     = "OR"

  documentation {
    content = <<-EOT
      the service is returning server errors

      What to do:
      Check the revision's logs; roll back to the previous revision if the errors started with a deployment.
    EOT
    mime_type = "text/markdown"
  }

  conditions {
    display_name = "seller-assistant-api-stg errors"
    condition_threshold {
      filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_count\"",
        "resource.label.\"project_id\"=\"${local.project_seller_app_stg_0}\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"seller-assistant-api-stg\"",
        "metric.label.\"response_code_class\"=\"5xx\"",
      ])
      comparison      = "COMPARISON_GT"
      threshold_value = 5
      duration        = "300s"
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  notification_channels = var.notification_channels
  severity              = "WARNING"
}

# --- Budget: seller-app-stg-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
resource "google_billing_budget" "seller-app-stg-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "seller-assistant in seller-app-stg-0"

  budget_filter {
    projects = ["projects/${local.project_seller_app_stg_0}"]
    labels = {
      application = "seller-assistant"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "200"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}

# --- Budget: seller-dp-stg-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
resource "google_billing_budget" "seller-dp-stg-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "seller-assistant in seller-dp-stg-0"

  budget_filter {
    projects = ["projects/${local.project_seller_dp_stg_0}"]
    labels = {
      application = "seller-assistant"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "200"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}
