# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Values arrive through the tfvars files 0-org-setup and 2-project-factory
# publish to the iac-outputs bucket; fetch them with fast-links.sh.

variable "prefix" {
  description = "Prefix for organization projects."
  type        = string
  nullable    = false
}

variable "project_ids" {
  description = "Project ids by key; project-factory ids are derived from the prefix when absent."
  type        = map(string)
  nullable    = false
  default     = {}
}
