# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Operations for checkout in prd.
#
# A stage that creates a service and no way to notice it failing is half a
# deliverable. Every alert below says what to do about it, because an alert
# whose runbook is "someone will know" is noise with a pager attached.
#
# The thresholds are Merlin's opinion, not your policy: they are the starting
# points Google's own SLO guidance recommends. Change them once you know what
# this application is actually for. CONFORMANCE.md records them as opinions.

variable "notification_channels" {
  description = "Channels to notify, from the landing zone's monitoring setup. Empty means the policies are created and notify nobody."
  type        = list(string)
  nullable    = false
  default     = []
}

# --- Objective: checkout-api-prd availability -----------
resource "google_monitoring_slo" "checkout-api-prd-availability" {
  project      = local.project_shop_app_prd_0
  service      = google_monitoring_custom_service.checkout-api-prd.service_id
  slo_id       = "checkout-api-prd-availability"
  display_name = "checkout-api-prd availability"

  goal                = 0.99
  rolling_period_days = 28

  request_based_sli {
    good_total_ratio {
      good_service_filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_count\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"checkout-api-prd\"",
        "metric.label.\"response_code_class\"!=\"5xx\"",
      ])
      total_service_filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_count\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"checkout-api-prd\"",
      ])
    }
  }
}

# --- Objective: checkout-api-prd latency -----------
resource "google_monitoring_slo" "checkout-api-prd-latency" {
  project      = local.project_shop_app_prd_0
  service      = google_monitoring_custom_service.checkout-api-prd.service_id
  slo_id       = "checkout-api-prd-latency"
  display_name = "checkout-api-prd latency"

  goal                = 0.95
  rolling_period_days = 28

  request_based_sli {
    distribution_cut {
      distribution_filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_latencies\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"checkout-api-prd\"",
      ])
      range {
        max = 1000
      }
    }
  }
}

# The service an objective is measured against.
resource "google_monitoring_custom_service" "checkout-api-prd" {
  project      = local.project_shop_app_prd_0
  service_id   = "checkout-api-prd"
  display_name = "checkout-api-prd"
}

# --- Alert: checkout-api-prd errors ------------------
# the service is returning server errors
resource "google_monitoring_alert_policy" "checkout-api-prd-errors" {
  project      = local.project_shop_app_prd_0
  display_name = "checkout-api-prd: the service is returning server errors"
  combiner     = "OR"

  documentation {
    content = <<-EOT
      the service is returning server errors

      What to do:
      Check the revision's logs; roll back to the previous revision if the errors started with a deployment.
    EOT
    mime_type = "text/markdown"
  }

  conditions {
    display_name = "checkout-api-prd errors"
    condition_threshold {
      filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/request_count\"",
        "resource.label.\"project_id\"=\"${local.project_shop_app_prd_0}\"",
        "resource.type=\"cloud_run_revision\"",
        "resource.label.\"service_name\"=\"checkout-api-prd\"",
        "metric.label.\"response_code_class\"=\"5xx\"",
      ])
      comparison      = "COMPARISON_GT"
      threshold_value = 5
      duration        = "300s"
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  notification_channels = var.notification_channels
  severity              = "WARNING"
}

# --- Alert: checkout-stream-processing-prd backlog ------------------
# the pipeline is falling behind its input
resource "google_monitoring_alert_policy" "checkout-stream-processing-prd-backlog" {
  project      = local.project_shop_dp_prd_0
  display_name = "checkout-stream-processing-prd: the pipeline is falling behind its input"
  combiner     = "OR"

  documentation {
    content = <<-EOT
      the pipeline is falling behind its input

      What to do:
      Check whether the pipeline is stuck on a bad message. Raise max_workers if the backlog is growing steadily rather than in a spike.
    EOT
    mime_type = "text/markdown"
  }

  conditions {
    display_name = "checkout-stream-processing-prd backlog"
    condition_threshold {
      filter = join(" AND ", [
        "metric.type=\"dataflow.googleapis.com/job/backlog_elapsed_seconds\"",
        "resource.label.\"project_id\"=\"${local.project_shop_dp_prd_0}\"",
        "resource.type=\"dataflow_job\"",
        "resource.label.\"job_name\"=\"checkout-stream-processing-prd\"",
      ])
      comparison      = "COMPARISON_GT"
      threshold_value = 600
      duration        = "300s"
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  notification_channels = var.notification_channels
  severity              = "WARNING"
}

# --- Alert: checkout-stream-processing-prd failed ------------------
# the pipeline has stopped
resource "google_monitoring_alert_policy" "checkout-stream-processing-prd-failed" {
  project      = local.project_shop_dp_prd_0
  display_name = "checkout-stream-processing-prd: the pipeline has stopped"
  combiner     = "OR"

  documentation {
    content = <<-EOT
      the pipeline has stopped

      What to do:
      A streaming pipeline that stops loses nothing yet: the messages wait. Restart it, then look at why it stopped.
    EOT
    mime_type = "text/markdown"
  }

  conditions {
    display_name = "checkout-stream-processing-prd failed"
    condition_threshold {
      filter = join(" AND ", [
        "metric.type=\"dataflow.googleapis.com/job/is_failed\"",
        "resource.label.\"project_id\"=\"${local.project_shop_dp_prd_0}\"",
        "resource.type=\"dataflow_job\"",
        "resource.label.\"job_name\"=\"checkout-stream-processing-prd\"",
      ])
      comparison      = "COMPARISON_GT"
      threshold_value = 1
      duration        = "300s"
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  notification_channels = var.notification_channels
  severity              = "WARNING"
}

# --- Budget: shop-app-prd-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
resource "google_billing_budget" "shop-app-prd-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "checkout in shop-app-prd-0"

  budget_filter {
    projects = ["projects/${local.project_shop_app_prd_0}"]
    labels = {
      application = "checkout"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "1000"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}

# --- Budget: shop-dp-prd-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
#
# This project runs checkout-stream-processing-prd, which bill from the
# first apply whether or not a message arrives. Size the amount for that
# floor, or this budget warns in the first week of an application nobody
# uses yet.
resource "google_billing_budget" "shop-dp-prd-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "checkout in shop-dp-prd-0"

  budget_filter {
    projects = ["projects/${local.project_shop_dp_prd_0}"]
    labels = {
      application = "checkout"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "1000"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}
