# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// Outputs of 3-app-checkout-prd, for the pipeline that deploys into it.

output "application" {
  description = "The application this stage belongs to."
  value       = "checkout"
}

output "environment" {
  description = "The environment this stage builds."
  value       = "prd"
}

output "service_accounts" {
  description = "Runtime identities, by node. Deploy as these, never as a key."
  value = {
    "api" = module.sa-checkout-api-prd.email
    "stream-processing" = module.sa-checkout-stream-processing-prd.email
  }
}

output "service_urls" {
  description = "Cloud Run service URLs. Reachable through the front door, not directly."
  value = {
    "checkout-api-prd" = module.run-checkout-api-prd.service_uri
  }
}

output "database_connection_names" {
  description = "Cloud SQL connection names, for the application's own configuration."
  value = {
    "checkout-relational-prd" = module.sql-checkout-relational-prd.connection_name
  }
  sensitive = false
}
