# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-delivery-pools -- Cloud Build private pools for Cloud Deploy.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Cloud Deploy renders and deploys in Cloud Build. Inside a VPC Service
# Controls perimeter the default pool is not allowed; these pools are what
# every application's targets run on instead. One per workload network, not
# one per application: a project holds at most ten pools per region, and
# every delivery stage lives in this central project.

locals {
  # Every resource in app-core-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_app_core_0 = one(distinct(concat(
    [for s in google_project_service.app_core_0 : s.project],
    [for s in google_project_service_identity.app_core_0 : s.project],
  )))
}

# --- Services this stage enables in app-core-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "app_core_0" {
  for_each = toset([
    "cloudbuild.googleapis.com",
    "clouddeploy.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "app-core-0", "${var.prefix}-app-core-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "app_core_0" {
  provider = google-beta
  for_each = toset([
    "clouddeploy.googleapis.com",
  ])
  project = google_project_service.app_core_0[each.key].project
  service = each.key
}


# The Cloud Deploy service agent starts the builds, so it is the one that has
# to be allowed to use the pools. Worker pools take no resource-level IAM,
# so this is the project, which holds nothing else Cloud Build runs on.
data "google_project" "central" {
  project_id = local.project_app_core_0
}

resource "google_project_iam_member" "clouddeploy-uses-pools" {
  project = local.project_app_core_0
  role    = "roles/cloudbuild.workerPoolUser"
  member  = "serviceAccount:service-${data.google_project.central.number}@gcp-sa-clouddeploy.iam.gserviceaccount.com"
}

# --- Pool: deploy-vpc-shared-dev ---------------------------------------------------
# For dev, stg, whose workloads are on vpc-shared-dev. Peered through the
# Private Service Access connection 2-networking makes on that network; the
# workers have no external address, which is the egress a perimeter requires.
resource "google_cloudbuild_worker_pool" "deploy_vpc_shared_dev" {
  project  = local.project_app_core_0
  name     = "deploy-vpc-shared-dev"
  location = "europe-west4"

  worker_config {
    machine_type   = "e2-standard-2"
    disk_size_gb   = 100
    no_external_ip = true
  }

  network_config {
    # The network's resource name, which the pool wants in the
    # projects/<host>/global/networks/<vpc> form rather than as a self link.
    peered_network = replace(var.vpc_self_links["vpc-shared-dev"], "https://www.googleapis.com/compute/v1/", "")
  }
}

# --- Pool: deploy-vpc-shared-prod ---------------------------------------------------
# For prd, whose workloads are on vpc-shared-prod. Peered through the
# Private Service Access connection 2-networking makes on that network; the
# workers have no external address, which is the egress a perimeter requires.
resource "google_cloudbuild_worker_pool" "deploy_vpc_shared_prod" {
  project  = local.project_app_core_0
  name     = "deploy-vpc-shared-prod"
  location = "europe-west4"

  worker_config {
    machine_type   = "e2-standard-2"
    disk_size_gb   = 100
    no_external_ip = true
  }

  network_config {
    # The network's resource name, which the pool wants in the
    # projects/<host>/global/networks/<vpc> form rather than as a self link.
    peered_network = replace(var.vpc_self_links["vpc-shared-prod"], "https://www.googleapis.com/compute/v1/", "")
  }
}

output "worker_pools" {
  description = "Worker pool resource names, by network."
  value = {
    "vpc-shared-dev" = google_cloudbuild_worker_pool.deploy_vpc_shared_dev.id
    "vpc-shared-prod" = google_cloudbuild_worker_pool.deploy_vpc_shared_prod.id
  }
}
