# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-app-inventory-replica-delivery -- how inventory-replica's code reaches the slots the
# other stages built.
#
# One stage rather than one per environment, because promotion is the point:
# a pipeline that only knows about production is not a pipeline. Promotion
# runs prd, and production is the one place a person
# approves before a release lands.
#
# Everything here lives in the central project beside the registry. A Cloud
# Deploy pipeline can only name targets in its own project and region, so a
# pipeline in one environment's project could never have promoted into
# another's.
#
# What Merlin does not produce is the build. A delivery pipeline needs to know
# how to turn this application's source into an image, and that lives in the
# application's repository. skaffold.example.yaml beside this file is an
# example, not a working configuration.

locals {
  # Every resource in app-core-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_app_core_0 = one(distinct(concat(
    [for s in google_project_service.app_core_0 : s.project],
    [for s in google_project_service_identity.app_core_0 : s.project],
  )))
  project_seller_app_prd_0 = lookup(var.project_ids, "seller-app-prd-0", "${var.prefix}-seller-app-prd-0")
}

# --- Services this stage enables in app-core-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "app_core_0" {
  for_each = toset([
    "clouddeploy.googleapis.com",
    "iam.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "app-core-0", "${var.prefix}-app-core-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "app_core_0" {
  provider = google-beta
  for_each = toset([
    "clouddeploy.googleapis.com",
  ])
  project = google_project_service.app_core_0[each.key].project
  service = each.key
}


# --- Registry: inventory-replica -------------------------------------
# Shared by every environment, because an image promoted between them has to
# be the same image. Vulnerability scanning is on: an image nobody scanned is
# an image nobody can vouch for.
module "registry-inventory-replica" {
  source        = "../../../modules/artifact-registry"
  project_id    = local.project_app_core_0
  name          = "inventory-replica"
  location      = "europe-west4"
  format        = { docker = { standard = {} } }
  description   = "Container images for inventory-replica"
  encryption_key = var.kms_keys["artifactregistry-kr-europe-west4"]
  labels = {
    application = "inventory-replica"
    managed-by  = "merlin"
  }
}

# prd's Cloud Run pulls images from here as its own
# service agent, which lives in another project.
resource "google_artifact_registry_repository_iam_member" "inventory_replica_pull_prd" {
  project    = local.project_app_core_0
  location   = "europe-west4"
  repository = module.registry-inventory-replica.name
  role       = "roles/artifactregistry.reader"
  member     = "serviceAccount:service-${data.google_project.project_seller_app_prd_0.number}@serverless-robot-prod.iam.gserviceaccount.com"
}

data "google_project" "project_seller_app_prd_0" {
  project_id = local.project_seller_app_prd_0
}

# --- Deploy identity -----------------------------------------------------
# Cloud Deploy renders and deploys as this account. Without one named on each
# target it uses the Compute Engine default service account of this project,
# which nobody chose and which holds whatever that project granted it.
module "sa-inventory-replica-deploy" {
  source      = "../../../modules/iam-service-account"
  project_id  = local.project_app_core_0
  name        = "inventory-replica-deploy"
  description = "Cloud Deploy runs inventory-replica's releases as this"
  iam_project_roles = {
    (local.project_app_core_0) = [
      "roles/clouddeploy.jobRunner",
    ]
  }
}

# --- Delivery pipeline ---------------------------------------------------
# The targets are created below rather than by the module: the module cannot
# name the identity a target deploys as.
module "delivery-inventory-replica" {
  source      = "../../../modules/cloud-deploy"
  project_id  = local.project_app_core_0
  region      = "europe-west4"
  name        = "inventory-replica"
  description = "Promotes inventory-replica through prd"

  targets = [
    {
      name          = "inventory-replica-prd"
      create_target = false
    },
  ]

  labels = {
    application = "inventory-replica"
    managed-by  = "merlin"
  }
}

resource "google_clouddeploy_target" "inventory_replica_prd" {
  project          = local.project_app_core_0
  location         = "europe-west4"
  name             = "inventory-replica-prd"
  description      = "inventory-replica in prd"
  # Production: a person looks before this lands.
  require_approval = true

  execution_configs {
    usages          = ["RENDER", "DEPLOY"]
    service_account = module.sa-inventory-replica-deploy.email
    # The private pool on vpc-shared-prod, from 3-delivery-pools: inside a VPC
    # Service Controls perimeter Cloud Deploy may not use the default pool.
    worker_pool     = "projects/${local.project_app_core_0}/locations/europe-west4/workerPools/deploy-vpc-shared-prod"
  }

  run {
    location = "projects/${local.project_seller_app_prd_0}/locations/europe-west4"
  }

  labels = {
    application = "inventory-replica"
    environment = "prd"
    managed-by  = "merlin"
  }
}
