# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 2-networking-endpoints -- Private Service Connect endpoints for regional Google APIs.
# Generated by Merlin Studio.
#
# Model Armor answers only at modelarmor.<region>.rep.googleapis.com, and a
# caller on a VPC reaches that name through a Private Service Connect endpoint
# or not at all: Private Google Access and VPC Service Controls produce a
# certificate error instead. Each endpoint below lives in the host network's
# project, takes an address from one of its subnets, and a private zone bound
# to the same network resolves the regional name to that address -- so an
# application calls Model Armor by its ordinary name and never knows.

# --- Model Armor in europe-west4 on vpc-shared-dev ---------------------------------
resource "google_network_connectivity_regional_endpoint" "modelarmor_vpc_shared_dev_europe_west4" {
  project           = split("/", var.vpc_self_links["vpc-shared-dev"])[1]
  location          = "europe-west4"
  name              = "modelarmor-vpc-shared-dev-europe-west4"
  description       = "Model Armor regional API for workloads on vpc-shared-dev"
  target_google_api = "modelarmor.europe-west4.rep.googleapis.com"
  access_type       = "REGIONAL"
  network           = var.vpc_self_links["vpc-shared-dev"]
  subnetwork        = var.subnet_self_links["vpc-shared-dev"]["europe-west4/sb-dev-europe-west4"]
}

resource "google_dns_managed_zone" "modelarmor_vpc_shared_dev_europe_west4" {
  project     = split("/", var.vpc_self_links["vpc-shared-dev"])[1]
  name        = "modelarmor-vpc-shared-dev-europe-west4"
  dns_name    = "modelarmor.europe-west4.rep.googleapis.com."
  description = "Resolves the Model Armor regional API to its Private Service Connect endpoint on vpc-shared-dev"
  visibility  = "private"

  private_visibility_config {
    networks {
      network_url = var.vpc_self_links["vpc-shared-dev"]
    }
  }
}

resource "google_dns_record_set" "modelarmor_vpc_shared_dev_europe_west4" {
  project      = split("/", var.vpc_self_links["vpc-shared-dev"])[1]
  managed_zone = google_dns_managed_zone.modelarmor_vpc_shared_dev_europe_west4.name
  name         = "modelarmor.europe-west4.rep.googleapis.com."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_network_connectivity_regional_endpoint.modelarmor_vpc_shared_dev_europe_west4.address]
}

# --- Model Armor in europe-west4 on vpc-shared-prod ---------------------------------
resource "google_network_connectivity_regional_endpoint" "modelarmor_vpc_shared_prod_europe_west4" {
  project           = split("/", var.vpc_self_links["vpc-shared-prod"])[1]
  location          = "europe-west4"
  name              = "modelarmor-vpc-shared-prod-europe-west4"
  description       = "Model Armor regional API for workloads on vpc-shared-prod"
  target_google_api = "modelarmor.europe-west4.rep.googleapis.com"
  access_type       = "REGIONAL"
  network           = var.vpc_self_links["vpc-shared-prod"]
  subnetwork        = var.subnet_self_links["vpc-shared-prod"]["europe-west4/sb-prod-europe-west4"]
}

resource "google_dns_managed_zone" "modelarmor_vpc_shared_prod_europe_west4" {
  project     = split("/", var.vpc_self_links["vpc-shared-prod"])[1]
  name        = "modelarmor-vpc-shared-prod-europe-west4"
  dns_name    = "modelarmor.europe-west4.rep.googleapis.com."
  description = "Resolves the Model Armor regional API to its Private Service Connect endpoint on vpc-shared-prod"
  visibility  = "private"

  private_visibility_config {
    networks {
      network_url = var.vpc_self_links["vpc-shared-prod"]
    }
  }
}

resource "google_dns_record_set" "modelarmor_vpc_shared_prod_europe_west4" {
  project      = split("/", var.vpc_self_links["vpc-shared-prod"])[1]
  managed_zone = google_dns_managed_zone.modelarmor_vpc_shared_prod_europe_west4.name
  name         = "modelarmor.europe-west4.rep.googleapis.com."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_network_connectivity_regional_endpoint.modelarmor_vpc_shared_prod_europe_west4.address]
}

output "model_armor_endpoints" {
  description = "Model Armor Private Service Connect endpoint addresses, by network and region."
  value = {
    "vpc-shared-dev/europe-west4" = google_network_connectivity_regional_endpoint.modelarmor_vpc_shared_dev_europe_west4.address
    "vpc-shared-prod/europe-west4" = google_network_connectivity_regional_endpoint.modelarmor_vpc_shared_prod_europe_west4.address
  }
}
