# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Values arrive through the tfvars file 2-networking publishes to the
# iac-outputs bucket (2-networking.auto.tfvars.json); fetch it with
# fast-links.sh.

variable "vpc_self_links" {
  description = "VPC ids from 2-networking, keyed by VPC: projects/<host>/global/networks/<vpc>."
  type        = map(string)
  nullable    = false
}

variable "subnet_self_links" {
  description = "Subnet ids from 2-networking, keyed by VPC then <region>/<subnet>."
  type        = map(map(string))
  nullable    = false
}
