# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-artifact-registry — container and package repositories.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Registries are central: one set of repositories serves every environment,
# so this stage has no environment suffix. It deploys into the shared
# application project the landing zone creates.

locals {
  project_id = lookup(var.project_ids, "app-core-0", "${var.prefix}-app-core-0")
}

# --- repository: containers (DOCKER) ----------------------------
module "registry-containers" {
  source         = "../../../modules/artifact-registry"
  project_id     = local.project_id
  name           = "containers"
  location       = "europe-west4"
  format         = { docker = { standard = {} } }
  encryption_key = var.kms_keys["artifactregistry-kr-europe-west4"]
  cleanup_policies = {
    keep-recent = {
      action = "KEEP"
      most_recent_versions = {
        keep_count = 10
      }
    }
  }
  labels = {
    managed-by = "merlin"
  }
}
