# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

output "repositories" {
  description = "Artifact Registry repository ids and URLs."
  value = {
    "containers" = {
      id  = module.registry-containers.id
      url = module.registry-containers.url
    }
  }
}
