# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# The confirm table, as values. The billing account's real value lives in
# deploy/seller.facts.env and is passed over this one. department_folder_ids and
# deploy_service_accounts arrive in core.auto.tfvars.json, written by
# deploy/apply-seller.sh from the core root's outputs.
prefix          = "vd"
primary_region  = "europe-west4"
billing_account = "FAKE00-356D6C-FD4FEF"
budget_currency = "EUR"
network_project = "vd-net-core-0"
vpc             = "vpc-shared-dev"
subnet_cidr     = "10.200.12.0/22"
