# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# The facts this root is built against. terraform.tfvars carries the ones from
# the confirm table; core.auto.tfvars.json carries what the core root created
# (written by deploy/apply-seller.sh from core's outputs).

variable "billing_account" {
  description = "Billing account id the department's projects are attached to."
  type        = string
  nullable    = false
}

variable "budget_currency" {
  description = "Currency of the billing account, for the budget."
  type        = string
  default     = "USD"
}

variable "department_folder_ids" {
  description = "The department's folder under each environment folder, from the core root's outputs."
  type        = map(string)
  nullable    = false
}

variable "deploy_service_accounts" {
  description = "The deploy identity of each environment, from the core root's outputs."
  type        = map(string)
  nullable    = false
}

variable "network_project" {
  description = "The host project of the environment's Shared VPC."
  type        = string
  nullable    = false
}

variable "prefix" {
  description = "The landing zone's project id prefix."
  type        = string
  nullable    = false
}

variable "primary_region" {
  description = "The region of the department's subnet."
  type        = string
  nullable    = false
}

variable "project_ids" {
  description = "Project ids by key, for the landing zone's own template; the department's projects are looked up in local.department_project_ids."
  type        = map(string)
  default     = {}
}

variable "subnet_cidr" {
  description = "The department's range in the environment's network."
  type        = string
  nullable    = false
}

variable "vpc" {
  description = "The environment's network, by name, in the host project."
  type        = string
  nullable    = false
}
