# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-app-seller-assistant-dev -- the "seller-assistant" application in dev.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Archetype AI2: Retrieval-augmented generation.
#
# Everything below was derived from the archetype's graph and the landing zone
# this application is compiled against. Each identity exists because a compute
# node runs as it; each binding exists because an edge of the graph needs it.
# CONFORMANCE.md in this bundle says which edge produced which grant, and which
# rule produced each setting.

locals {
  # Every resource in seller-app-dev-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_seller_app_dev_0 = one(distinct(concat(
    [for s in google_project_service.seller_app_dev_0 : s.project],
    [for s in google_project_service_identity.seller_app_dev_0 : s.project],
  )))
  # Every resource in seller-dp-dev-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_seller_dp_dev_0 = one(distinct(concat(
    [for s in google_project_service.seller_dp_dev_0 : s.project],
    [for s in google_project_service_identity.seller_dp_dev_0 : s.project],
  )))
  project_sec_core_0 = lookup(var.project_ids, "sec-core-0", "${var.prefix}-sec-core-0")
  project_app_core_0 = lookup(var.project_ids, "app-core-0", "${var.prefix}-app-core-0")
}

# --- Services this stage enables in seller-app-dev-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "seller_app_dev_0" {
  for_each = toset([
    "compute.googleapis.com",
    "iam.googleapis.com",
    "modelarmor.googleapis.com",
    "monitoring.googleapis.com",
    "run.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "seller-app-dev-0", "${var.prefix}-seller-app-dev-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "seller_app_dev_0" {
  provider = google-beta
  for_each = toset([
    "modelarmor.googleapis.com",
    "monitoring.googleapis.com",
    "run.googleapis.com",
  ])
  project = google_project_service.seller_app_dev_0[each.key].project
  service = each.key
}

# --- Services this stage enables in seller-dp-dev-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "seller_dp_dev_0" {
  for_each = toset([
    "aiplatform.googleapis.com",
    "pubsub.googleapis.com",
    "storage.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "seller-dp-dev-0", "${var.prefix}-seller-dp-dev-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "seller_dp_dev_0" {
  provider = google-beta
  for_each = toset([
    "aiplatform.googleapis.com",
    "pubsub.googleapis.com",
  ])
  project = google_project_service.seller_dp_dev_0[each.key].project
  service = each.key
}


# --- Keys this stage owns -------------------------------------------------
# A framework in force requires customer-managed encryption and the landing
# zone wired no key into these projects for these services -- it wires one
# for each service a project already enables, and an application introduces
# services the landing zone never heard of.
#
# The keys live in the landing zone's key project, beside the keys it made --
# the people who hold keys are not the people who hold the data -- in a
# keyring this application owns, never the landing zone's own. Each is in
# the location of the resource it encrypts, because a key is only usable
# from there. Rotation is the shortest period any framework in force asks for.
#
# Where the landing zone wires a key for a service, this stage uses that one
# and creates none: enable the service on the Security page and regenerate
# the landing zone to move a key there.
resource "google_kms_key_ring" "app_seller_assistant_dev_europe_west4" {
  project  = local.project_sec_core_0
  name     = "app-seller-assistant-dev-europe-west4"
  location = "europe-west4"
}

# Cloud Storage buckets and objects
resource "google_kms_crypto_key" "app_seller_assistant_dev_europe_west4_storage" {
  name            = "storage"
  key_ring        = google_kms_key_ring.app_seller_assistant_dev_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_seller_assistant_dev_europe_west4_storage_seller_dp_dev_0_1" {
  crypto_key_id = google_kms_crypto_key.app_seller_assistant_dev_europe_west4_storage.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_seller_dp_dev_0.number}@gs-project-accounts.iam.gserviceaccount.com"
}

# Vertex AI datasets, models, endpoints
resource "google_kms_crypto_key" "app_seller_assistant_dev_europe_west4_vertexai" {
  name            = "vertexai"
  key_ring        = google_kms_key_ring.app_seller_assistant_dev_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_seller_assistant_dev_europe_west4_vertexai_seller_dp_dev_0_1" {
  crypto_key_id = google_kms_crypto_key.app_seller_assistant_dev_europe_west4_vertexai.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_seller_dp_dev_0.number}@gcp-sa-aiplatform.iam.gserviceaccount.com"
}

# Pub/Sub message encryption
resource "google_kms_crypto_key" "app_seller_assistant_dev_europe_west4_pubsub" {
  name            = "pubsub"
  key_ring        = google_kms_key_ring.app_seller_assistant_dev_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_seller_assistant_dev_europe_west4_pubsub_seller_dp_dev_0_1" {
  crypto_key_id = google_kms_crypto_key.app_seller_assistant_dev_europe_west4_pubsub.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_seller_dp_dev_0.number}@gcp-sa-pubsub.iam.gserviceaccount.com"
}

# The service agent's address contains the project number, which is not the
# project id and is not known until the project exists.
data "google_project" "project_seller_dp_dev_0" {
  project_id = local.project_seller_dp_dev_0
}




# --- Runtime identity: seller-assistant-embedding-dev -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-seller-assistant-embedding-dev" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_seller_app_dev_0
  name        = "seller-assistant-embedding-dev"
  description = "Runtime identity for embeddings (dev)"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}


# --- Runtime identity: seller-assistant-api-dev -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-seller-assistant-api-dev" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_seller_app_dev_0
  name        = "seller-assistant-api-dev"
  description = "Runtime identity for api (dev)"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}

# --- What delivery may do here ------------------------------------------
# The delivery pipeline deploys as seller-assistant-deploy, which the
# delivery stage creates in the central project. It can deploy into this
# environment because this environment's stage says so -- not because the
# delivery identity holds a role here, which would make one identity able to
# change every environment.
resource "google_project_iam_member" "delivery-deploys-into-dev" {
  project = local.project_seller_app_dev_0
  role    = "roles/run.developer"
  member  = "serviceAccount:seller-assistant-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# A release runs as seller-assistant-api-dev, and whoever deploys it has to be allowed to
# say so.
resource "google_service_account_iam_member" "delivery-acts-as-seller-assistant-api-dev" {
  service_account_id = module.sa-seller-assistant-api-dev.id
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:seller-assistant-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# A release runs as seller-assistant-embedding-dev, and whoever deploys it has to be allowed to
# say so.
resource "google_service_account_iam_member" "delivery-acts-as-seller-assistant-embedding-dev" {
  service_account_id = module.sa-seller-assistant-embedding-dev.id
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:seller-assistant-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# --- Front door: seller-assistant-internet-dev -----------------------------------------
# The only way in. seller-assistant-api-dev accepts traffic from this load
# balancer and nothing else, so a request that skips the firewall policy has
# nowhere to arrive.
module "lb-seller-assistant-internet-dev" {
  source     = "../../../modules/net-lb-app-ext"
  project_id = local.project_seller_app_dev_0
  name       = "seller-assistant-internet-dev"
  protocol = "HTTPS"
  ssl_certificates = {
    managed_configs = {
      default = {
        # A placeholder until you own the name. The certificate stays
        # PROVISIONING until this domain resolves to the address below, which
        # the preflight checks and the README explains.
        domains = ["seller-assistant-dev.example.com"]
      }
    }
  }

  # A serverless endpoint group is how a load balancer reaches Cloud Run:
  # there is no instance to put in a backend.
  neg_configs = {
    default = {
      cloudrun = {
        region         = "europe-west4"
        target_service = { name = "seller-assistant-api-dev" }
      }
    }
  }

  backend_service_configs = {
    default = {
      backends = [{ group = "default" }]
      # The landing zone's own policy, attached by name. This layer never
      # writes rule content: that belongs to the Security page.
      security_policy = "compliance-waf-policy"
      log_config = {
        enable      = true
        sample_rate = 1
      }
    }
  }

  labels = {
    application = "seller-assistant"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Cloud Run service: seller-assistant-embeddings-dev -------------------------------
module "run-seller-assistant-embeddings-dev" {
  source     = "../../../modules/cloud-run-v2"
  project_id = local.project_seller_app_dev_0
  name       = "seller-assistant-embeddings-dev"
  region     = "europe-west4"
  containers = {
    app = {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
      resources = {
        limits = {
          cpu    = "2"
          memory = "1Gi"
        }
      }
    }
  }
  service_config = {
    ingress = "INGRESS_TRAFFIC_INTERNAL_ONLY"
    scaling = {
      min_instance_count = 0
      max_instance_count = 10
    }
  }
  service_account_config = {
    # The identity is created above, because the edges of the graph grant to
    # it; the service only attaches to it. Letting the module create its own
    # would give the workload an identity nothing had granted anything.
    create = false
    email  = module.sa-seller-assistant-embedding-dev.email
  }
  deletion_protection = false
  labels = {
    application = "seller-assistant"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Cloud Run service: seller-assistant-api-dev -------------------------------
module "run-seller-assistant-api-dev" {
  source     = "../../../modules/cloud-run-v2"
  project_id = local.project_seller_app_dev_0
  name       = "seller-assistant-api-dev"
  region     = "europe-west4"
  containers = {
    app = {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
      resources = {
        limits = {
          cpu    = "1"
          memory = "512Mi"
        }
      }
    }
  }
  service_config = {
    ingress = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
    max_concurrency = 80
    scaling = {
      min_instance_count = 1
      max_instance_count = 50
    }
  }
  revision = {
    timeout = "300s"
    vpc_access = {
      network = var.vpc_self_links["vpc-shared-dev"]
      subnet  = var.subnet_self_links["vpc-shared-dev"]["europe-west4/sb-seller-dev-europe-west4"]
      egress  = "PRIVATE_RANGES_ONLY"
    }
  }
  service_account_config = {
    # The identity is created above, because the edges of the graph grant to
    # it; the service only attaches to it. Letting the module create its own
    # would give the workload an identity nothing had granted anything.
    create = false
    email  = module.sa-seller-assistant-api-dev.email
  }
  deletion_protection = false
  labels = {
    application = "seller-assistant"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Bucket: seller-assistant-objects-dev -------------------------------------------
# Public access prevention is enforced rather than merely unset: a bucket
# that can be made public later is a bucket that will be.
module "bucket-seller-assistant-objects-dev" {
  source                      = "../../../modules/gcs"
  project_id                  = local.project_seller_dp_dev_0
  name                        = "seller-assistant-objects-dev"
  location                    = "EUROPE-WEST4"
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
  public_access_prevention    = "enforced"
  versioning                  = true
  force_destroy               = false
  encryption_key = google_kms_crypto_key.app_seller_assistant_dev_europe_west4_storage.id
  labels = {
    application = "seller-assistant"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Topic: seller-assistant-events-dev ---------------------------------------------
module "topic-seller-assistant-events-dev" {
  source     = "../../../modules/pubsub"
  project_id = local.project_seller_dp_dev_0
  name       = "seller-assistant-events-dev"
  # Messages are stored only where the residency policy allows.
  regions = ["europe-west4"]
  message_retention_duration = "86400s"
  kms_key = google_kms_crypto_key.app_seller_assistant_dev_europe_west4_pubsub.id
  labels = {
    application = "seller-assistant"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Model guardrail: seller-assistant-llm-dev -------------------------------------
# There is no model here. Gemini is reached at a regional API endpoint, and
# which model this application calls is a line in its own code -- it changes
# with the release cycle and does not belong pinned in Terraform.
#
# What this is, is the screening every prompt and every response should pass
# through -- and the honest word is "should". The application applies this
# template on each call; nothing in this stage can force it to, because the
# identity that calls the model is the same identity either way.
#
# What does force it is a Model Armor floor setting, which is set on the
# organisation or the folder and applies to every project underneath. That
# belongs to the landing zone rather than to one application, so Merlin does
# not write it here. If you need the guarantee rather than the intention,
# ask for it there.
resource "google_model_armor_template" "seller-assistant-llm-dev" {
  provider    = google-beta
  project     = local.project_seller_app_dev_0
  location    = "europe-west4"
  template_id = "seller-assistant-llm-dev"

  filter_config {
    # Personal data detected and de-identified before the model sees it.
    # This one is a control, not a preference: GDPR Article 25 and the HIPAA
    # Security Rule both name DLP scanning, and CONFORMANCE.md cites them.
    sdp_settings {
      basic_config {
        filter_enforcement = "ENABLED"
      }
    }
    # Injection and jailbreak screening. No framework in this landing zone
    # requires it: it is Merlin's opinion, and turning it off costs nothing
    # in the conformance record.
    pi_and_jailbreak_filter_settings {
      filter_enforcement = "ENABLED"
      confidence_level   = "MEDIUM_AND_ABOVE"
    }
    rai_settings {
      rai_filters {
        filter_type      = "DANGEROUS"
        confidence_level = "MEDIUM_AND_ABOVE"
      }
      rai_filters {
        filter_type      = "HATE_SPEECH"
        confidence_level = "MEDIUM_AND_ABOVE"
      }
      rai_filters {
        filter_type      = "HARASSMENT"
        confidence_level = "MEDIUM_AND_ABOVE"
      }
      rai_filters {
        filter_type      = "SEXUALLY_EXPLICIT"
        confidence_level = "MEDIUM_AND_ABOVE"
      }
    }
  }

  # What was asked and what was answered, kept for 30
  # days. It is an audit record and it is also a copy of whatever the prompt
  # contained, which is why it stays in this application's own project.
  template_metadata {
    log_sanitize_operations    = true
    log_template_operations    = true
  }
}

# --- Vector index: seller-assistant-vectors-dev -----------------------------------------
# Passages stored by meaning. The index is cheap to keep and the endpoint
# below is not: it is charged while it is deployed, asked or not.
resource "google_vertex_ai_index" "seller-assistant-vectors-dev" {
  project      = local.project_seller_dp_dev_0
  region       = "europe-west4"
  display_name = "seller-assistant-vectors-dev"
  description  = "Retrieval corpus for seller-assistant"

  metadata {
    config {
      dimensions                  = 768
      approximate_neighbors_count = 150
      # Has to match what the embedding model was trained for, and cannot be
      # changed once the index is built.
      distance_measure_type = "COSINE_DISTANCE"
      algorithm_config {
        tree_ah_config {
          leaf_node_embedding_count    = 500
          leaf_nodes_to_search_percent = 7
        }
      }
    }
  }
  index_update_method = "STREAM_UPDATE"
  encryption_spec {
    kms_key_name = google_kms_crypto_key.app_seller_assistant_dev_europe_west4_vertexai.id
  }
}

resource "google_vertex_ai_index_endpoint" "seller-assistant-vectors-dev" {
  project      = local.project_seller_dp_dev_0
  region       = "europe-west4"
  display_name = "seller-assistant-vectors-dev"
  description  = "Private endpoint for seller-assistant-vectors-dev"

  # Reached from inside the VPC and from nowhere else. A public index
  # endpoint is a corpus with an address: enough of the source text can be
  # recovered from enough queries.
  private_service_connect_config {
    enable_private_service_connect = true
    project_allowlist              = [local.project_seller_dp_dev_0]
  }
  encryption_spec {
    kms_key_name = google_kms_crypto_key.app_seller_assistant_dev_europe_west4_vertexai.id
  }
}

# --- Grants that land on one resource ------------------------------------
# Each names the edge that produced it. A role with a resource-scoped form is
# never widened to the project: that is what makes the least-privilege claim
# in CONFORMANCE.md checkable rather than decorative.
resource "google_storage_bucket_iam_member" "seller-assistant-embedding-dev-roles-storage-objectviewer-seller-assistant-objects-dev" {
  # objects -> embeddings
  bucket = module.bucket-seller-assistant-objects-dev.name
  role   = "roles/storage.objectViewer"
  member = module.sa-seller-assistant-embedding-dev.iam_email
}
resource "google_pubsub_topic_iam_member" "seller-assistant-embedding-dev-roles-pubsub-subscriber-seller-assistant-events-dev" {
  # events -> embeddings
  project = local.project_seller_dp_dev_0
  topic = module.topic-seller-assistant-events-dev.id
  role   = "roles/pubsub.subscriber"
  member = module.sa-seller-assistant-embedding-dev.iam_email
}
resource "google_pubsub_topic_iam_member" "seller-assistant-embedding-dev-roles-pubsub-viewer-seller-assistant-events-dev" {
  # events -> embeddings
  project = local.project_seller_dp_dev_0
  topic = module.topic-seller-assistant-events-dev.id
  role   = "roles/pubsub.viewer"
  member = module.sa-seller-assistant-embedding-dev.iam_email
}

# --- Grants the edges of the graph imply ---------------------------------
# Each binding names the edge that produced it. A role that no edge can
# account for is a defect, and the least-privilege gate fails on it.
resource "google_project_iam_member" "seller-assistant-embedding-dev-roles-aiplatform-user-seller-assistant-vectors-dev" {
  # embeddings -> vectors -- project-scoped because Vertex AI exposes no resource-level IAM for an index: the role is granted on the data project. Every application in the environment shares that project, so the grant also reaches the other applications' indexes (P7).
  project = local.project_seller_dp_dev_0
  role    = "roles/aiplatform.user"
  member  = module.sa-seller-assistant-embedding-dev.iam_email
}
resource "google_project_iam_member" "seller-assistant-api-dev-roles-aiplatform-user-seller-assistant-vectors-dev" {
  # api -> vectors -- project-scoped because Vertex AI exposes no resource-level IAM for an index: the role is granted on the data project. Every application in the environment shares that project, so the grant also reaches the other applications' indexes (P7).
  project = local.project_seller_dp_dev_0
  role    = "roles/aiplatform.user"
  member  = module.sa-seller-assistant-api-dev.iam_email
}
resource "google_project_iam_member" "seller-assistant-api-dev-roles-aiplatform-user-seller-assistant-llm-dev" {
  # api -> llm -- project-scoped because Vertex AI exposes no resource-level IAM for a managed foundation model: `aiplatform.user` is granted on the application project. Every application in the environment shares that project, so the grant also reaches the AI resources the others created there (P7).
  project = local.project_seller_app_dev_0
  role    = "roles/aiplatform.user"
  member  = module.sa-seller-assistant-api-dev.iam_email
}
