# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// Outputs of 3-app-seller-assistant-dev, for the pipeline that deploys into it.

output "application" {
  description = "The application this stage belongs to."
  value       = "seller-assistant"
}

output "environment" {
  description = "The environment this stage builds."
  value       = "dev"
}

output "service_accounts" {
  description = "Runtime identities, by node. Deploy as these, never as a key."
  value = {
    "embeddings" = module.sa-seller-assistant-embedding-dev.email
    "api" = module.sa-seller-assistant-api-dev.email
  }
}

output "service_urls" {
  description = "Cloud Run service URLs. Reachable through the front door, not directly."
  value = {
    "seller-assistant-embeddings-dev" = module.run-seller-assistant-embeddings-dev.service_uri
    "seller-assistant-api-dev" = module.run-seller-assistant-api-dev.service_uri
  }
}
