# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# What the environment roots read. deploy/apply-shop.sh writes these
# into each environment root's core.auto.tfvars.json, so no root reads
# another's state.

output "department_folder_ids" {
  description = "The department's folder under each environment folder."
  value = {
    dev = module.folder-dev.id
    stg = module.folder-stg.id
    prd = module.folder-prd.id
  }
}

output "deploy_service_accounts" {
  description = "The deploy identity of each environment."
  value = {
    dev = module.sa-iac-dev.email
    stg = module.sa-iac-stg.email
    prd = module.sa-iac-prd.email
  }
}

output "core_project_id" {
  value = module.project-core.project_id
}

output "core_project_number" {
  value = module.project-core.number
}

output "state_bucket" {
  description = "Every root of this department keeps its state here, under its own prefix."
  value       = module.bucket-state.name
}

output "key_ring_id" {
  value = module.kms.id
}

output "default_key_id" {
  value = module.kms.key_ids["shop-default"]
}
