# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# The facts this root is built against. Every one of them names something
# that exists in your organisation; terraform.tfvars carries the values the
# confirm table showed, and deploy/preflight-shop.sh checks them.

variable "billing_account" {
  description = "Billing account id the department's projects are attached to."
  type        = string
  nullable    = false
}

variable "environment_folders" {
  description = "The landing zone's environment folders, by environment code, as folders/<number>."
  type        = map(string)
  nullable    = false
}

variable "shared_services_folder" {
  description = "The landing zone's Shared Services folder, as folders/<number>; the core project is created under it."
  type        = string
  nullable    = false
}

variable "key_project" {
  description = "The landing zone's central key project, when it has one; the department's key ring is created in it, else in the core project."
  type        = string
  default     = ""
}

variable "prefix" {
  description = "The landing zone's project id prefix."
  type        = string
  nullable    = false
}

variable "primary_region" {
  description = "Where the state bucket and the key ring live."
  type        = string
  nullable    = false
}

variable "customer_id" {
  description = "Cloud Identity customer id (customers/C0xxxxxxx), only when this root creates the department's groups."
  type        = string
  default     = ""
}
