# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Operations for storefront in stg.
#
# A stage that creates a service and no way to notice it failing is half a
# deliverable. Every alert below says what to do about it, because an alert
# whose runbook is "someone will know" is noise with a pager attached.
#
# The thresholds are Merlin's opinion, not your policy: they are the starting
# points Google's own SLO guidance recommends. Change them once you know what
# this application is actually for. CONFORMANCE.md records them as opinions.

variable "notification_channels" {
  description = "Channels to notify, from the landing zone's monitoring setup. Empty means the policies are created and notify nobody."
  type        = list(string)
  nullable    = false
  default     = []
}

# --- Budget: shop-app-stg-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
resource "google_billing_budget" "shop-app-stg-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "storefront in shop-app-stg-0"

  budget_filter {
    projects = ["projects/${local.project_shop_app_stg_0}"]
    labels = {
      application = "storefront"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "200"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}

# --- Budget: shop-dp-stg-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
resource "google_billing_budget" "shop-dp-stg-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "storefront in shop-dp-stg-0"

  budget_filter {
    projects = ["projects/${local.project_shop_dp_stg_0}"]
    labels = {
      application = "storefront"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "200"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}
