# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// Outputs of 3-app-storefront-stg, for the pipeline that deploys into it.

output "application" {
  description = "The application this stage belongs to."
  value       = "storefront"
}

output "environment" {
  description = "The environment this stage builds."
  value       = "stg"
}

output "service_accounts" {
  description = "Runtime identities, by node. Deploy as these, never as a key."
  value = {
    "services" = module.sa-storefront-services-stg.email
  }
}

output "database_connection_names" {
  description = "Cloud SQL connection names, for the application's own configuration."
  value = {
    "storefront-relational-stg" = module.sql-storefront-relational-stg.connection_name
  }
  sensitive = false
}
