#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Apply the "Seller Platform" department (seller) on top of the landing zone.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
#   ./deploy/apply-seller.sh /path/to/fabric-checkout               # plan, then apply
#   ./deploy/apply-seller.sh /path/to/fabric-checkout --plan-only   # plan only
#   ./deploy/apply-seller.sh /path/to/fabric-checkout --env dev     # one environment root
#
# Order: the preflight, then DEPARTMENT-seller/core (once; its state moves into
# the bucket it creates), then one root per environment. Merlin applies
# nothing itself; this is the sequence written out.
set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAST_DIR="${1:-${FAST_CHECKOUT:-}}"
shift || true

PLAN_ONLY=0
ONLY_ENV=""
while [ $# -gt 0 ]; do
  case "$1" in
    --plan-only) PLAN_ONLY=1 ;;
    --env) ONLY_ENV="${2:-}"; shift ;;
    *) printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
  shift
done

if [ -z "${FAST_DIR}" ] || [ ! -d "${FAST_DIR}/modules" ]; then
  printf 'usage: ./deploy/apply-seller.sh /path/to/fabric-checkout [--plan-only] [--env CODE]\n' >&2
  exit 2
fi
command -v jq >/dev/null || { printf 'jq is required to pass the core root outputs on\n' >&2; exit 2; }

STAGES_DIR="${FAST_DIR}/fast/stages"
ROOT="DEPARTMENT-seller"
STATE_BUCKET="vd-seller-iac-state"

# The facts have to be true of the real organisation before anything is created.
"${BUNDLE_DIR}/deploy/preflight-seller.sh"

# The organisation's own facts, from the one file they are kept in. They
# reach each root as facts.auto.tfvars.json, which Terraform reads after
# terraform.tfvars, so the placeholders there need no edit.
# shellcheck disable=SC1091
. "${BUNDLE_DIR}/deploy/seller.facts.env"

stage_dir() {
  local dest="${STAGES_DIR}/${ROOT}/$1"
  mkdir -p "${dest}"
  cp -r "${BUNDLE_DIR}/${ROOT}/$1/." "${dest}/"
  if [ "$1" = "core" ]; then
    jq -n --arg billing "${BILLING_ACCOUNT}" --arg shared "${SHARED_SERVICES_FOLDER}" --arg f_dev "${FOLDER_DEV}" --arg f_stg "${FOLDER_STG}" --arg f_prd "${FOLDER_PRD}" \
      '{billing_account: $billing, shared_services_folder: $shared, environment_folders: { "dev": $f_dev, "stg": $f_stg, "prd": $f_prd }}' \
      > "${dest}/facts.auto.tfvars.json"
  else
    jq -n --arg billing "${BILLING_ACCOUNT}" '{billing_account: $billing}' > "${dest}/facts.auto.tfvars.json"
  fi
  printf '%s' "${dest}"
}

plan_apply() {
  terraform plan -input=false -out=tfplan
  if [ "${PLAN_ONLY}" -eq 0 ]; then
    terraform apply -input=false tfplan
  fi
}

# --- core: once -------------------------------------------------------------
if [ -z "${ONLY_ENV}" ]; then
  printf '\n=== %s/core\n' "${ROOT}"
  CORE_DIR="$(stage_dir core)"
  ( cd "${CORE_DIR}"
    if gsutil ls -b "gs://${STATE_BUCKET}" >/dev/null 2>&1; then
      # The bucket exists: the state is already in it.
      terraform init -input=false -backend-config="bucket=${STATE_BUCKET}" -backend-config="prefix=core"
    else
      # First run: local state until the bucket this root creates exists.
      terraform init -input=false -backend=false
    fi
    plan_apply
    if [ "${PLAN_ONLY}" -eq 0 ] && [ ! -f .terraform/terraform.tfstate ]; then
      terraform init -input=false -migrate-state -force-copy \
        -backend-config="bucket=${STATE_BUCKET}" -backend-config="prefix=core"
    fi
    terraform output -json > "${BUNDLE_DIR}/${ROOT}/core-outputs.json" )
fi

if [ ! -f "${BUNDLE_DIR}/${ROOT}/core-outputs.json" ]; then
  printf 'no core outputs yet: apply the core root first\n' >&2
  exit 2
fi

# --- one root per environment -----------------------------------------------
if [ -z "${ONLY_ENV}" ] || [ "${ONLY_ENV}" = "dev" ]; then
  printf '\n=== %s/dev\n' "${ROOT}"
  ENV_DIR="$(stage_dir dev)"
  jq '{department_folder_ids: .department_folder_ids.value, deploy_service_accounts: .deploy_service_accounts.value}' \
    "${BUNDLE_DIR}/${ROOT}/core-outputs.json" > "${ENV_DIR}/core.auto.tfvars.json"
  ( cd "${ENV_DIR}"
    terraform init -input=false -backend-config="bucket=${STATE_BUCKET}" -backend-config="prefix=dev"
    plan_apply )
fi
if [ -z "${ONLY_ENV}" ] || [ "${ONLY_ENV}" = "stg" ]; then
  printf '\n=== %s/stg\n' "${ROOT}"
  ENV_DIR="$(stage_dir stg)"
  jq '{department_folder_ids: .department_folder_ids.value, deploy_service_accounts: .deploy_service_accounts.value}' \
    "${BUNDLE_DIR}/${ROOT}/core-outputs.json" > "${ENV_DIR}/core.auto.tfvars.json"
  ( cd "${ENV_DIR}"
    terraform init -input=false -backend-config="bucket=${STATE_BUCKET}" -backend-config="prefix=stg"
    plan_apply )
fi
if [ -z "${ONLY_ENV}" ] || [ "${ONLY_ENV}" = "prd" ]; then
  printf '\n=== %s/prd\n' "${ROOT}"
  ENV_DIR="$(stage_dir prd)"
  jq '{department_folder_ids: .department_folder_ids.value, deploy_service_accounts: .deploy_service_accounts.value}' \
    "${BUNDLE_DIR}/${ROOT}/core-outputs.json" > "${ENV_DIR}/core.auto.tfvars.json"
  ( cd "${ENV_DIR}"
    terraform init -input=false -backend-config="bucket=${STATE_BUCKET}" -backend-config="prefix=prd"
    plan_apply )
fi

printf '\nDone. MERLIN_DEPARTMENT.json in this bundle is what the application layer places against.\n'
