#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Preflight for the "Seller Platform" department (seller).
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# The confirm table said what the landing zone looks like. A deployed landing
# zone may differ from Merlin's picture of it, so before anything is created
# this checks every fact against the real organisation, and checks that the
# identity running it may create what the roots create. Read-only.
set -uo pipefail

FAIL=0
ok()   { printf '  ok   %s\n' "$1"; }
bad()  { printf '  FAIL %s\n' "$1"; FAIL=1; }
note() { printf '  note %s\n' "$1"; }

# The organisation's own facts: the billing account and the folder numbers.
# shellcheck disable=SC1091
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/seller.facts.env"

# Merlin's placeholders are not facts: say where the real ones go and stop there.
placeholder() {
  case "$1" in FAKE00-*|folders/0*) return 0 ;; *) return 1 ;; esac
}

TOKEN="$(gcloud auth print-access-token 2>/dev/null || true)"
[ -n "${TOKEN}" ] || { printf 'gcloud is not logged in\n' >&2; exit 2; }

# testIamPermissions on a resource: prints the permissions the caller lacks.
lacks() {
  local url="$1"; shift
  local body
  body="$(printf '%s\n' "$@" | jq -R . | jq -s '{permissions: .}')"
  local granted
  granted="$(curl -s -X POST -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" \
    -d "${body}" "${url}" | jq -r '.permissions[]?' 2>/dev/null)"
  for permission in "$@"; do
    printf '%s\n' "${granted}" | grep -qx "${permission}" || printf '%s ' "${permission}"
  done
}

printf '\n== Folders\n'
for folder in "${SHARED_SERVICES_FOLDER}" "${FOLDER_DEV}" "${FOLDER_STG}" "${FOLDER_PRD}"; do
  number="${folder#folders/}"
  if placeholder "${folder}"; then
    bad "${folder} is Merlin's placeholder: put the real folder in deploy/seller.facts.env"
  elif gcloud resource-manager folders describe "${number}" --format="value(displayName)" >/dev/null 2>&1; then
    ok "${folder} exists ($(gcloud resource-manager folders describe "${number}" --format='value(displayName)'))"
    missing="$(lacks "https://cloudresourcemanager.googleapis.com/v3/${folder}:testIamPermissions" \
      resourcemanager.folders.create resourcemanager.projects.create)"
    [ -z "${missing}" ] && ok "may create folders and projects under ${folder}" || bad "lacks on ${folder}: ${missing}"
  else
    bad "${folder} not found, or not visible to this identity"
  fi
done

printf '\n== Network\n'
NET="vd-net-core-0"
if gcloud projects describe "${NET}" >/dev/null 2>&1; then
  ok "dev: host project ${NET} exists"
  missing="$(lacks "https://cloudresourcemanager.googleapis.com/v1/projects/${NET}:testIamPermissions" \
    compute.subnetworks.create compute.subnetworks.setIamPolicy)"
  [ -z "${missing}" ] && ok "dev: may create subnets in ${NET}" || bad "dev: lacks in ${NET}: ${missing}"
else
  bad "dev: host project ${NET} not found"
fi
if gcloud compute networks describe "vpc-shared-dev" --project="${NET}" >/dev/null 2>&1; then
  ok "dev: network vpc-shared-dev exists"
  if gcloud compute networks subnets list --project="${NET}" --filter="network:vpc-shared-dev AND name=sb-seller-dev-europe-west4" --format="value(name)" 2>/dev/null | grep -q .; then
    note "dev: subnet sb-seller-dev-europe-west4 already exists (a previous apply, or a name in use)"
  fi
  if command -v python3 >/dev/null; then
    gcloud compute networks subnets list --project="${NET}" --filter="network:vpc-shared-dev" \
      --format="value(ipCidrRange,secondaryIpRanges[].ipCidrRange)" 2>/dev/null \
      | tr ';' '\n' | tr -d ' ' | grep . \
      | python3 -c 'import ipaddress,sys
wanted=ipaddress.ip_network("10.200.12.0/22")
clash=[l.strip() for l in sys.stdin if l.strip() and ipaddress.ip_network(l.strip()).overlaps(wanted)]
sys.exit(1 if clash else 0)' \
      && ok "dev: 10.200.12.0/22 overlaps no subnet of vpc-shared-dev" \
      || bad "dev: 10.200.12.0/22 overlaps a range already in vpc-shared-dev"
  else
    note "dev: python3 not found, the range 10.200.12.0/22 was not checked for overlap"
  fi
else
  bad "dev: network vpc-shared-dev not found in ${NET}"
fi
NET="vd-net-core-0"
if gcloud projects describe "${NET}" >/dev/null 2>&1; then
  ok "stg: host project ${NET} exists"
  missing="$(lacks "https://cloudresourcemanager.googleapis.com/v1/projects/${NET}:testIamPermissions" \
    compute.subnetworks.create compute.subnetworks.setIamPolicy)"
  [ -z "${missing}" ] && ok "stg: may create subnets in ${NET}" || bad "stg: lacks in ${NET}: ${missing}"
else
  bad "stg: host project ${NET} not found"
fi
if gcloud compute networks describe "vpc-shared-dev" --project="${NET}" >/dev/null 2>&1; then
  ok "stg: network vpc-shared-dev exists"
  if gcloud compute networks subnets list --project="${NET}" --filter="network:vpc-shared-dev AND name=sb-seller-stg-europe-west4" --format="value(name)" 2>/dev/null | grep -q .; then
    note "stg: subnet sb-seller-stg-europe-west4 already exists (a previous apply, or a name in use)"
  fi
  if command -v python3 >/dev/null; then
    gcloud compute networks subnets list --project="${NET}" --filter="network:vpc-shared-dev" \
      --format="value(ipCidrRange,secondaryIpRanges[].ipCidrRange)" 2>/dev/null \
      | tr ';' '\n' | tr -d ' ' | grep . \
      | python3 -c 'import ipaddress,sys
wanted=ipaddress.ip_network("10.200.16.0/22")
clash=[l.strip() for l in sys.stdin if l.strip() and ipaddress.ip_network(l.strip()).overlaps(wanted)]
sys.exit(1 if clash else 0)' \
      && ok "stg: 10.200.16.0/22 overlaps no subnet of vpc-shared-dev" \
      || bad "stg: 10.200.16.0/22 overlaps a range already in vpc-shared-dev"
  else
    note "stg: python3 not found, the range 10.200.16.0/22 was not checked for overlap"
  fi
else
  bad "stg: network vpc-shared-dev not found in ${NET}"
fi
NET="vd-net-core-0"
if gcloud projects describe "${NET}" >/dev/null 2>&1; then
  ok "prd: host project ${NET} exists"
  missing="$(lacks "https://cloudresourcemanager.googleapis.com/v1/projects/${NET}:testIamPermissions" \
    compute.subnetworks.create compute.subnetworks.setIamPolicy)"
  [ -z "${missing}" ] && ok "prd: may create subnets in ${NET}" || bad "prd: lacks in ${NET}: ${missing}"
else
  bad "prd: host project ${NET} not found"
fi
if gcloud compute networks describe "vpc-shared-prod" --project="${NET}" >/dev/null 2>&1; then
  ok "prd: network vpc-shared-prod exists"
  if gcloud compute networks subnets list --project="${NET}" --filter="network:vpc-shared-prod AND name=sb-seller-prd-europe-west4" --format="value(name)" 2>/dev/null | grep -q .; then
    note "prd: subnet sb-seller-prd-europe-west4 already exists (a previous apply, or a name in use)"
  fi
  if command -v python3 >/dev/null; then
    gcloud compute networks subnets list --project="${NET}" --filter="network:vpc-shared-prod" \
      --format="value(ipCidrRange,secondaryIpRanges[].ipCidrRange)" 2>/dev/null \
      | tr ';' '\n' | tr -d ' ' | grep . \
      | python3 -c 'import ipaddress,sys
wanted=ipaddress.ip_network("10.200.20.0/22")
clash=[l.strip() for l in sys.stdin if l.strip() and ipaddress.ip_network(l.strip()).overlaps(wanted)]
sys.exit(1 if clash else 0)' \
      && ok "prd: 10.200.20.0/22 overlaps no subnet of vpc-shared-prod" \
      || bad "prd: 10.200.20.0/22 overlaps a range already in vpc-shared-prod"
  else
    note "prd: python3 not found, the range 10.200.20.0/22 was not checked for overlap"
  fi
else
  bad "prd: network vpc-shared-prod not found in ${NET}"
fi

printf '\n== Keys\n'
KEYS="vd-sec-core-0"
if gcloud projects describe "${KEYS}" >/dev/null 2>&1; then
  ok "key project ${KEYS} exists"
  missing="$(lacks "https://cloudresourcemanager.googleapis.com/v1/projects/${KEYS}:testIamPermissions" \
    cloudkms.keyRings.create cloudkms.cryptoKeys.create)"
  [ -z "${missing}" ] && ok "may create key rings in ${KEYS}" || bad "lacks in ${KEYS}: ${missing}"
else
  bad "key project ${KEYS} not found"
fi

printf '\n== Billing\n'
BILLING="${BILLING_ACCOUNT}"
if placeholder "${BILLING}"; then
  bad "billing account ${BILLING} is Merlin's placeholder: put your own in deploy/seller.facts.env (Merlin never asks for it)"
elif gcloud billing accounts describe "${BILLING}" >/dev/null 2>&1; then
  ok "billing account ${BILLING} is visible"
  missing="$(lacks "https://cloudbilling.googleapis.com/v1/billingAccounts/${BILLING}:testIamPermissions" \
    billing.resourceAssociations.create)"
  [ -z "${missing}" ] && ok "may attach projects to ${BILLING}" || bad "lacks on ${BILLING}: ${missing}"
else
  bad "billing account ${BILLING} not found, or not visible to this identity"
fi

printf '\n== Projects\n'
for key in "seller-core-0" "seller-app-dev-0" "seller-dp-dev-0" "seller-app-stg-0" "seller-dp-stg-0" "seller-app-prd-0" "seller-dp-prd-0"; do
  if gcloud projects describe "vd-${key}" >/dev/null 2>&1; then
    note "vd-${key} already exists (a previous apply, or an id in use)"
  else
    ok "vd-${key} is free"
  fi
done

printf '\n== Groups (prerequisites: this root binds them, it does not create them)\n'
for group in "gcp-seller-developers@vendora.eu" "gcp-seller-qa@vendora.eu" "gcp-seller-owners@vendora.eu"; do
  if gcloud identity groups describe "${group}" >/dev/null 2>&1; then
    ok "group ${group} exists"
  else
    bad "group ${group} not found: create it, or set create_groups in the department"
  fi
done

printf '\n'
if [ "${FAIL}" -ne 0 ]; then
  printf 'Preflight failed. Fix the lines marked FAIL, or correct the facts in the roots'"'"' terraform.tfvars.\n'
  exit 1
fi
printf 'Preflight passed.\n'
