# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-app-inventory-replica-prd -- the "inventory-replica" application in prd.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Archetype H3: Database replication to the cloud.
#
# Everything below was derived from the archetype's graph and the landing zone
# this application is compiled against. Each identity exists because a compute
# node runs as it; each binding exists because an edge of the graph needs it.
# CONFORMANCE.md in this bundle says which edge produced which grant, and which
# rule produced each setting.

locals {
  # Every resource in seller-dp-prd-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_seller_dp_prd_0 = one(distinct(concat(
    [for s in google_project_service.seller_dp_prd_0 : s.project],
    [for s in google_project_service_identity.seller_dp_prd_0 : s.project],
  )))
  # Every resource in seller-app-prd-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_seller_app_prd_0 = one(distinct(concat(
    [for s in google_project_service.seller_app_prd_0 : s.project],
    [for s in google_project_service_identity.seller_app_prd_0 : s.project],
  )))
  project_sec_core_0 = lookup(var.project_ids, "sec-core-0", "${var.prefix}-sec-core-0")
  project_app_core_0 = lookup(var.project_ids, "app-core-0", "${var.prefix}-app-core-0")
}

# --- Services this stage enables in seller-dp-prd-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "seller_dp_prd_0" {
  for_each = toset([
    "bigquery.googleapis.com",
    "datamigration.googleapis.com",
    "iam.googleapis.com",
    "sqladmin.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "seller-dp-prd-0", "${var.prefix}-seller-dp-prd-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "seller_dp_prd_0" {
  provider = google-beta
  for_each = toset([
    "datamigration.googleapis.com",
    "sqladmin.googleapis.com",
  ])
  project = google_project_service.seller_dp_prd_0[each.key].project
  service = each.key
}

# --- Services this stage enables in seller-app-prd-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "seller_app_prd_0" {
  for_each = toset([
    "cloudscheduler.googleapis.com",
    "iam.googleapis.com",
    "monitoring.googleapis.com",
    "run.googleapis.com",
    "secretmanager.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "seller-app-prd-0", "${var.prefix}-seller-app-prd-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "seller_app_prd_0" {
  provider = google-beta
  for_each = toset([
    "cloudscheduler.googleapis.com",
    "monitoring.googleapis.com",
    "run.googleapis.com",
    "secretmanager.googleapis.com",
  ])
  project = google_project_service.seller_app_prd_0[each.key].project
  service = each.key
}


# --- Keys this stage owns -------------------------------------------------
# A framework in force requires customer-managed encryption and the landing
# zone wired no key into these projects for these services -- it wires one
# for each service a project already enables, and an application introduces
# services the landing zone never heard of.
#
# The keys live in the landing zone's key project, beside the keys it made --
# the people who hold keys are not the people who hold the data -- in a
# keyring this application owns, never the landing zone's own. Each is in
# the location of the resource it encrypts, because a key is only usable
# from there. Rotation is the shortest period any framework in force asks for.
#
# Where the landing zone wires a key for a service, this stage uses that one
# and creates none: enable the service on the Security page and regenerate
# the landing zone to move a key there.
resource "google_kms_key_ring" "app_inventory_replica_prd_europe_west4" {
  project  = local.project_sec_core_0
  name     = "app-inventory-replica-prd-europe-west4"
  location = "europe-west4"
}

# Cloud SQL instances
resource "google_kms_crypto_key" "app_inventory_replica_prd_europe_west4_cloudsql" {
  name            = "cloudsql"
  key_ring        = google_kms_key_ring.app_inventory_replica_prd_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_inventory_replica_prd_europe_west4_cloudsql_seller_dp_prd_0_1" {
  crypto_key_id = google_kms_crypto_key.app_inventory_replica_prd_europe_west4_cloudsql.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_seller_dp_prd_0.number}@gcp-sa-cloud-sql.iam.gserviceaccount.com"
}

# BigQuery datasets and tables
resource "google_kms_crypto_key" "app_inventory_replica_prd_europe_west4_bigquery" {
  name            = "bigquery"
  key_ring        = google_kms_key_ring.app_inventory_replica_prd_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_inventory_replica_prd_europe_west4_bigquery_seller_dp_prd_0_1" {
  crypto_key_id = google_kms_crypto_key.app_inventory_replica_prd_europe_west4_bigquery.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:bq-${data.google_project.project_seller_dp_prd_0.number}@bigquery-encryption.iam.gserviceaccount.com"
}

# The service agent's address contains the project number, which is not the
# project id and is not known until the project exists.
data "google_project" "project_seller_dp_prd_0" {
  project_id = local.project_seller_dp_prd_0
}




# --- Runtime identity: inventory-replica-replicat-prd -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-inventory-replica-replicat-prd" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_seller_dp_prd_0
  name        = "inventory-replica-replicat-prd"
  description = "Runtime identity for replicate (prd)"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}


# --- Runtime identity: inventory-replica-schedule-prd -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-inventory-replica-schedule-prd" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_seller_app_prd_0
  name        = "inventory-replica-schedule-prd"
  description = "Runtime identity for schedule (prd)"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}


# --- Runtime identity: inventory-replica-job-prd -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-inventory-replica-job-prd" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_seller_app_prd_0
  name        = "inventory-replica-job-prd"
  description = "Runtime identity for job (prd)"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}

# --- What delivery may do here ------------------------------------------
# The delivery pipeline deploys as inventory-replica-deploy, which the
# delivery stage creates in the central project. It can deploy into this
# environment because this environment's stage says so -- not because the
# delivery identity holds a role here, which would make one identity able to
# change every environment.
resource "google_project_iam_member" "delivery-deploys-into-prd" {
  project = local.project_seller_app_prd_0
  role    = "roles/run.developer"
  member  = "serviceAccount:inventory-replica-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# A release runs as inventory-replica-job-prd, and whoever deploys it has to be allowed to
# say so.
resource "google_service_account_iam_member" "delivery-acts-as-inventory-replica-job-prd" {
  service_account_id = module.sa-inventory-replica-job-prd.id
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:inventory-replica-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# --- Cloud Run service: inventory-replica-job-prd -------------------------------
module "run-inventory-replica-job-prd" {
  source     = "../../../modules/cloud-run-v2"
  project_id = local.project_seller_app_prd_0
  name       = "inventory-replica-job-prd"
  region     = "europe-west4"
  # A job is the same product as a service with a different type, which is
  # why one target realisation covers both.
  type = "JOB"
  job_config = {
    max_retries = 3
    timeout     = "3600s"
  }
  containers = {
    app = {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
      resources = {
        limits = {
          cpu    = "1"
          memory = "512Mi"
        }
      }
    }
  }
  revision = {
    vpc_access = {
      network = var.vpc_self_links["vpc-shared-prod"]
      subnet  = var.subnet_self_links["vpc-shared-prod"]["europe-west4/sb-seller-prd-europe-west4"]
      egress  = "PRIVATE_RANGES_ONLY"
    }
  }
  service_account_config = {
    # The identity is created above, because the edges of the graph grant to
    # it; the service only attaches to it. Letting the module create its own
    # would give the workload an identity nothing had granted anything.
    create = false
    email  = module.sa-inventory-replica-job-prd.email
  }
  deletion_protection = false
  labels = {
    application = "inventory-replica"
    environment = "prd"
    managed-by  = "merlin"
  }
}

# --- Cloud SQL instance: inventory-replica-relational-prd -----------------------------
# No public address, private connectivity onto this environment's own VPC.
module "sql-inventory-replica-relational-prd" {
  source              = "../../../modules/cloudsql-instance"
  project_id          = local.project_seller_dp_prd_0
  name                = "inventory-replica-relational-prd"
  region              = "europe-west4"
  database_version    = "MYSQL_8_0"
  tier                = "db-custom-2-7680"
  availability_type   = "REGIONAL"
  network_config = {
    # Private Service Access onto this environment's own VPC: no public
    # IPv4, and no authorized network list to keep correct over time.
    connectivity = {
      public_ipv4 = false
      psa_config = {
        private_network = var.vpc_self_links["vpc-shared-prod"]
      }
    }
  }
  ssl = {
    mode = "ENCRYPTED_ONLY"
  }
  # inventory-replica-replicate-prd replicates into this instance, and a
  # replication destination has to be empty: the source's databases arrive
  # with the replica, so none is created here.
  encryption_key_name = google_kms_crypto_key.app_inventory_replica_prd_europe_west4_cloudsql.id
  backup_configuration = {
    # Off while it is a replica, which the service manages; on after promotion.
    enabled                        = !var.inventory_replica_replicate_prd_replicating
    point_in_time_recovery_enabled = !var.inventory_replica_replicate_prd_replicating
  }
  # Google's attribute applies on every surface; Terraform's only stops a
  # careless apply. Production sets both.
  gcp_deletion_protection       = true
  terraform_deletion_protection = true
  labels = {
    application = "inventory-replica"
    environment = "prd"
    managed-by  = "merlin"
  }
}

# --- Secret: inventory-replica-db-prd -------------------------------------------
# The container only. The value is added out of band, so it never passes
# through a specification, a bundle or a state file.
module "secret-inventory-replica-db-prd" {
  source     = "../../../modules/secret-manager"
  project_id = local.project_seller_app_prd_0
  secrets = {
    # The accessor is set on the secret itself: the module takes iam per
    # secret, not for the whole project.
    "inventory-replica-db-prd" = {
      iam = {
        "roles/secretmanager.secretAccessor" = [module.sa-inventory-replica-job-prd.iam_email]
      }
    }
  }
}

# --- Dataset: inventory_replica_warehouse_prd -----------------------------------------
module "dataset-inventory-replica-warehouse-prd" {
  source     = "../../../modules/bigquery-dataset"
  project_id = local.project_seller_dp_prd_0
  id         = "inventory_replica_warehouse_prd"
  location   = "europe-west4"
  encryption_key = google_kms_crypto_key.app_inventory_replica_prd_europe_west4_bigquery.id
  options = {
    delete_contents_on_destroy = false
  }
  labels = {
    application = "inventory-replica"
    environment = "prd"
    managed-by  = "merlin"
  }
}

# --- Replication: inventory-replica-replicate-prd ---------------------------------------
# A continuous copy of the on-premises database into inventory-replica-relational-prd.
# The source keeps serving; this is a feed rather than a cutover.
#
# The source host and its credential are yours, not Merlin's, and they are
# variables with no default: a plan without them stops and names the missing
# one, rather than applying a placeholder. The password is sensitive, so it
# is kept out of plan output -- it is still written to state, as every
# credential this resource takes is, so the state bucket's access is the
# boundary. It used to be a literal in this file.
# Placeholder: the on-premises database inventory-replica-replicate-prd replicates from.
variable "inventory_replica_replicate_prd_source_host" {
  description = "Hostname or address of the on-premises database inventory-replica-replicate-prd replicates from."
  type        = string
  nullable    = false
  validation {
    condition     = length(trimspace(var.inventory_replica_replicate_prd_source_host)) > 0
    error_message = "Name the source database's host."
  }
}

# Placeholder: the replication user on that database.
variable "inventory_replica_replicate_prd_source_username" {
  description = "Replication user on the source database."
  type        = string
  nullable    = false
}

# Placeholder: that user's password, from your secret store at plan time.
variable "inventory_replica_replicate_prd_source_password" {
  description = "Password of the replication user. Supply it from your secret store at plan time."
  type        = string
  sensitive   = true
  nullable    = false
}

resource "google_database_migration_service_connection_profile" "inventory-replica-replicate-prd-source" {
  project               = local.project_seller_dp_prd_0
  location              = "europe-west4"
  connection_profile_id = "inventory-replica-replicate-prd-source"
  display_name          = "inventory-replica-replicate-prd-source"

  mysql {
    host     = var.inventory_replica_replicate_prd_source_host
    port     = 3306
    username = var.inventory_replica_replicate_prd_source_username
    password = var.inventory_replica_replicate_prd_source_password
  }
}

# The destination is inventory-replica-relational-prd, the instance this stage creates
# and the application reads -- not a second instance Database Migration
# Service creates beside it. A `cloudsql { settings }` profile makes the
# service create its own, so the replica and the database the application
# queried were two instances and the application never saw a replicated row.
resource "google_database_migration_service_connection_profile" "inventory-replica-replicate-prd-destination" {
  project               = local.project_seller_dp_prd_0
  location              = "europe-west4"
  connection_profile_id = "inventory-replica-replicate-prd-destination"
  display_name          = "inventory-replica-replicate-prd-destination"

  mysql {
    cloud_sql_id = module.sql-inventory-replica-relational-prd.name
  }
}

# While it replicates, inventory-replica-relational-prd is a read replica of the source:
# Database Migration Service demotes it and manages its backups. This says
# so to the instance above, which otherwise re-enables them on the next apply
# and breaks the replica. Set it to false after promoting the instance, and
# apply again: backups and point-in-time recovery come back.
variable "inventory_replica_replicate_prd_replicating" {
  description = "Whether inventory-replica-replicate-prd is still replicating into inventory-replica-relational-prd. Set to false after promotion."
  type        = bool
  nullable    = false
  default     = true
}

resource "google_database_migration_service_migration_job" "inventory-replica-replicate-prd" {
  project          = local.project_seller_dp_prd_0
  location         = "europe-west4"
  migration_job_id = "inventory-replica-replicate-prd"
  display_name     = "inventory-replica-replicate-prd"
  # Copy what is already there, then follow changes. The one-time mode is a
  # migration: it copies once and stops, which reads as a working replica
  # until someone queries a row that changed afterwards.
  type             = "CONTINUOUS"
  source           = google_database_migration_service_connection_profile.inventory-replica-replicate-prd-source.name
  destination      = google_database_migration_service_connection_profile.inventory-replica-replicate-prd-destination.name

  # Created, not started. An existing destination has to be demoted before
  # the job starts, which Terraform cannot do; deploy/replicate-inventory-replica-replicate-prd.sh
  # checks the instance is empty, demotes it, verifies the job and starts it.
  # Once started, the job's state is the service's, not this file's.
  desired_state = "NOT_STARTED"

  # The service reaches the source by peering into the landing zone's VPC and
  # crossing the hybrid link from there. The source keeps no public address.
  vpc_peering_connectivity {
    vpc = var.vpc_self_links["vpc-shared-prod"]
  }

  lifecycle {
    ignore_changes = [desired_state]
  }
}

# --- Schedule: inventory-replica-schedule-prd ---------------------------------------
# The clock authenticates as its own identity, which is the only thing
# granted permission to start inventory-replica-job-prd.
resource "google_cloud_scheduler_job" "inventory-replica-schedule-prd" {
  project     = local.project_seller_app_prd_0
  name        = "inventory-replica-schedule-prd"
  region      = "europe-west4"
  schedule    = "0 2 1-31 1-12 0-6"
  time_zone   = "Etc/UTC"
  description = "Starts inventory-replica-job-prd"

  retry_config {
    retry_count = 3
  }

  http_target {
    http_method = "POST"
    uri = format(
      "https://%s-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/%s/jobs/%s:run",
      "europe-west4", local.project_seller_app_prd_0, "inventory-replica-job-prd",
    )
    oauth_token {
      service_account_email = module.sa-inventory-replica-schedule-prd.email
    }
  }
}

# --- Grants that land on one resource ------------------------------------
# Each names the edge that produced it. A role with a resource-scoped form is
# never widened to the project: that is what makes the least-privilege claim
# in CONFORMANCE.md checkable rather than decorative.
resource "google_cloud_run_v2_job_iam_member" "inventory-replica-schedule-prd-roles-run-invoker-inventory-replica-job-prd" {
  # schedule -> job
  name = module.run-inventory-replica-job-prd.id
  role   = "roles/run.invoker"
  member = module.sa-inventory-replica-schedule-prd.iam_email
}
resource "google_bigquery_dataset_iam_member" "inventory-replica-job-prd-roles-bigquery-dataeditor-inventory-replica-warehouse-prd" {
  # job -> warehouse
  project = local.project_seller_dp_prd_0
  dataset_id = module.dataset-inventory-replica-warehouse-prd.dataset_id
  role   = "roles/bigquery.dataEditor"
  member = module.sa-inventory-replica-job-prd.iam_email
}

# --- Grants the edges of the graph imply ---------------------------------
# Each binding names the edge that produced it. A role that no edge can
# account for is a defect, and the least-privilege gate fails on it.
resource "google_project_iam_member" "inventory-replica-replicat-prd-roles-cloudsql-client-inventory-replica-relational-prd" {
  # replicate -> relational -- project-scoped because Cloud SQL exposes no resource-level IAM: `cloudsql.client` can only be granted on the project that holds the instance. That data project holds the instances of every application in the environment, so the binding carries an IAM condition on this instance's resource name; without it the identity could connect to all of them (P7).
  project = local.project_seller_dp_prd_0
  role    = "roles/cloudsql.client"
  member  = module.sa-inventory-replica-replicat-prd.iam_email
  condition {
    title      = "only inventory-replica-relational-prd"
    expression = "resource.name == 'projects/${local.project_seller_dp_prd_0}/instances/${module.sql-inventory-replica-relational-prd.name}' && resource.service == 'sqladmin.googleapis.com'"
  }
}
resource "google_project_iam_member" "inventory-replica-job-prd-roles-cloudsql-client-inventory-replica-relational-prd" {
  # job -> relational -- project-scoped because Cloud SQL exposes no resource-level IAM: `cloudsql.client` can only be granted on the project that holds the instance. That data project holds the instances of every application in the environment, so the binding carries an IAM condition on this instance's resource name; without it the identity could connect to all of them (P7).
  project = local.project_seller_dp_prd_0
  role    = "roles/cloudsql.client"
  member  = module.sa-inventory-replica-job-prd.iam_email
  condition {
    title      = "only inventory-replica-relational-prd"
    expression = "resource.name == 'projects/${local.project_seller_dp_prd_0}/instances/${module.sql-inventory-replica-relational-prd.name}' && resource.service == 'sqladmin.googleapis.com'"
  }
}
resource "google_project_iam_member" "inventory-replica-job-prd-roles-cloudsql-instanceuser-inventory-replica-relational-prd" {
  # job -> relational -- project-scoped because Cloud SQL exposes no resource-level IAM: `cloudsql.client` can only be granted on the project that holds the instance. That data project holds the instances of every application in the environment, so the binding carries an IAM condition on this instance's resource name; without it the identity could connect to all of them (P7).
  project = local.project_seller_dp_prd_0
  role    = "roles/cloudsql.instanceUser"
  member  = module.sa-inventory-replica-job-prd.iam_email
  condition {
    title      = "only inventory-replica-relational-prd"
    expression = "resource.name == 'projects/${local.project_seller_dp_prd_0}/instances/${module.sql-inventory-replica-relational-prd.name}' && resource.service == 'sqladmin.googleapis.com'"
  }
}
resource "google_project_iam_member" "inventory-replica-job-prd-roles-bigquery-jobuser-seller-dp-prd-0" {
  # job -> warehouse -- project-scoped because Running a load job is a project-level permission in BigQuery: there is no dataset-scoped equivalent of `bigquery.jobUser`.
  project = local.project_seller_dp_prd_0
  role    = "roles/bigquery.jobUser"
  member  = module.sa-inventory-replica-job-prd.iam_email
}
