# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Operations for inventory-replica in prd.
#
# A stage that creates a service and no way to notice it failing is half a
# deliverable. Every alert below says what to do about it, because an alert
# whose runbook is "someone will know" is noise with a pager attached.
#
# The thresholds are Merlin's opinion, not your policy: they are the starting
# points Google's own SLO guidance recommends. Change them once you know what
# this application is actually for. CONFORMANCE.md records them as opinions.

variable "notification_channels" {
  description = "Channels to notify, from the landing zone's monitoring setup. Empty means the policies are created and notify nobody."
  type        = list(string)
  nullable    = false
  default     = []
}

# --- Alert: inventory-replica-job-prd failed ------------------
# the scheduled job failed its last run
resource "google_monitoring_alert_policy" "inventory-replica-job-prd-failed" {
  project      = local.project_seller_app_prd_0
  display_name = "inventory-replica-job-prd: the scheduled job failed its last run"
  combiner     = "OR"

  documentation {
    content = <<-EOT
      the scheduled job failed its last run

      What to do:
      Look at the execution's logs. A job that fails every run since a deployment is a bad image; one that fails occasionally is usually its input.
    EOT
    mime_type = "text/markdown"
  }

  conditions {
    display_name = "inventory-replica-job-prd failed"
    condition_threshold {
      filter = join(" AND ", [
        "metric.type=\"run.googleapis.com/job/completed_task_attempt_count\"",
        "resource.label.\"project_id\"=\"${local.project_seller_app_prd_0}\"",
        "resource.type=\"cloud_run_job\"",
        "resource.label.\"job_name\"=\"inventory-replica-job-prd\"",
        "metric.label.\"result\"=\"failed\"",
      ])
      comparison      = "COMPARISON_GT"
      threshold_value = 1
      duration        = "300s"
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  notification_channels = var.notification_channels
  severity              = "WARNING"
}

# --- Budget: seller-app-prd-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
resource "google_billing_budget" "seller-app-prd-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "inventory-replica in seller-app-prd-0"

  budget_filter {
    projects = ["projects/${local.project_seller_app_prd_0}"]
    labels = {
      application = "inventory-replica"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "1000"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}

# --- Budget: seller-dp-prd-0 ----------------------------------------
# A starting line, not a forecast: Merlin cannot know what this application
# should cost. What it can do is make sure a runaway is noticed in days
# rather than at the end of the month. Change the amount once you know.
resource "google_billing_budget" "seller-dp-prd-0" {
  count = var.billing_account.id == null ? 0 : 1

  billing_account = var.billing_account.id
  display_name    = "inventory-replica in seller-dp-prd-0"

  budget_filter {
    projects = ["projects/${local.project_seller_dp_prd_0}"]
    labels = {
      application = "inventory-replica"
    }
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units         = "1000"
    }
  }

  threshold_rules {
    threshold_percent = 0.5
  }
  threshold_rules {
    threshold_percent = 0.9
  }
  threshold_rules {
    threshold_percent = 1.0
  }
}
