# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// Outputs of 3-app-inventory-replica-prd, for the pipeline that deploys into it.

output "application" {
  description = "The application this stage belongs to."
  value       = "inventory-replica"
}

output "environment" {
  description = "The environment this stage builds."
  value       = "prd"
}

output "service_accounts" {
  description = "Runtime identities, by node. Deploy as these, never as a key."
  value = {
    "replicate" = module.sa-inventory-replica-replicat-prd.email
    "schedule" = module.sa-inventory-replica-schedule-prd.email
    "job" = module.sa-inventory-replica-job-prd.email
  }
}

output "service_urls" {
  description = "Cloud Run service URLs. Reachable through the front door, not directly."
  value = {
    "inventory-replica-job-prd" = module.run-inventory-replica-job-prd.service_uri
  }
}

output "database_connection_names" {
  description = "Cloud SQL connection names, for the application's own configuration."
  value = {
    "inventory-replica-relational-prd" = module.sql-inventory-replica-relational-prd.connection_name
  }
  sensitive = false
}
