# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-app-checkout-stg -- the "checkout" application in stg.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Archetype A3: API with event analytics.
#
# Everything below was derived from the archetype's graph and the landing zone
# this application is compiled against. Each identity exists because a compute
# node runs as it; each binding exists because an edge of the graph needs it.
# CONFORMANCE.md in this bundle says which edge produced which grant, and which
# rule produced each setting.

locals {
  # Every resource in shop-app-stg-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_shop_app_stg_0 = one(distinct(concat(
    [for s in google_project_service.shop_app_stg_0 : s.project],
    [for s in google_project_service_identity.shop_app_stg_0 : s.project],
  )))
  # Every resource in shop-dp-stg-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_shop_dp_stg_0 = one(distinct(concat(
    [for s in google_project_service.shop_dp_stg_0 : s.project],
    [for s in google_project_service_identity.shop_dp_stg_0 : s.project],
  )))
  project_sec_core_0 = lookup(var.project_ids, "sec-core-0", "${var.prefix}-sec-core-0")
  project_app_core_0 = lookup(var.project_ids, "app-core-0", "${var.prefix}-app-core-0")
}

# --- Services this stage enables in shop-app-stg-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "shop_app_stg_0" {
  for_each = toset([
    "compute.googleapis.com",
    "iam.googleapis.com",
    "monitoring.googleapis.com",
    "run.googleapis.com",
    "secretmanager.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "shop-app-stg-0", "${var.prefix}-shop-app-stg-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "shop_app_stg_0" {
  provider = google-beta
  for_each = toset([
    "monitoring.googleapis.com",
    "run.googleapis.com",
    "secretmanager.googleapis.com",
  ])
  project = google_project_service.shop_app_stg_0[each.key].project
  service = each.key
}

# --- Services this stage enables in shop-dp-stg-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "shop_dp_stg_0" {
  for_each = toset([
    "bigquery.googleapis.com",
    "dataflow.googleapis.com",
    "iam.googleapis.com",
    "monitoring.googleapis.com",
    "pubsub.googleapis.com",
    "sqladmin.googleapis.com",
    "storage.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "shop-dp-stg-0", "${var.prefix}-shop-dp-stg-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "shop_dp_stg_0" {
  provider = google-beta
  for_each = toset([
    "dataflow.googleapis.com",
    "monitoring.googleapis.com",
    "pubsub.googleapis.com",
    "sqladmin.googleapis.com",
  ])
  project = google_project_service.shop_dp_stg_0[each.key].project
  service = each.key
}


# --- Keys this stage owns -------------------------------------------------
# A framework in force requires customer-managed encryption and the landing
# zone wired no key into these projects for these services -- it wires one
# for each service a project already enables, and an application introduces
# services the landing zone never heard of.
#
# The keys live in the landing zone's key project, beside the keys it made --
# the people who hold keys are not the people who hold the data -- in a
# keyring this application owns, never the landing zone's own. Each is in
# the location of the resource it encrypts, because a key is only usable
# from there. Rotation is the shortest period any framework in force asks for.
#
# Where the landing zone wires a key for a service, this stage uses that one
# and creates none: enable the service on the Security page and regenerate
# the landing zone to move a key there.
resource "google_kms_key_ring" "app_checkout_stg_europe_west4" {
  project  = local.project_sec_core_0
  name     = "app-checkout-stg-europe-west4"
  location = "europe-west4"
}

# Cloud SQL instances
resource "google_kms_crypto_key" "app_checkout_stg_europe_west4_cloudsql" {
  name            = "cloudsql"
  key_ring        = google_kms_key_ring.app_checkout_stg_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_checkout_stg_europe_west4_cloudsql_shop_dp_stg_0_1" {
  crypto_key_id = google_kms_crypto_key.app_checkout_stg_europe_west4_cloudsql.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_shop_dp_stg_0.number}@gcp-sa-cloud-sql.iam.gserviceaccount.com"
}

# Pub/Sub message encryption
resource "google_kms_crypto_key" "app_checkout_stg_europe_west4_pubsub" {
  name            = "pubsub"
  key_ring        = google_kms_key_ring.app_checkout_stg_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_checkout_stg_europe_west4_pubsub_shop_dp_stg_0_1" {
  crypto_key_id = google_kms_crypto_key.app_checkout_stg_europe_west4_pubsub.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_shop_dp_stg_0.number}@gcp-sa-pubsub.iam.gserviceaccount.com"
}

# Dataflow job state and shuffle data
resource "google_kms_crypto_key" "app_checkout_stg_europe_west4_dataflow" {
  name            = "dataflow"
  key_ring        = google_kms_key_ring.app_checkout_stg_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_checkout_stg_europe_west4_dataflow_shop_dp_stg_0_1" {
  crypto_key_id = google_kms_crypto_key.app_checkout_stg_europe_west4_dataflow.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_shop_dp_stg_0.number}@dataflow-service-producer-prod.iam.gserviceaccount.com"
}
resource "google_kms_crypto_key_iam_member" "app_checkout_stg_europe_west4_dataflow_shop_dp_stg_0_2" {
  crypto_key_id = google_kms_crypto_key.app_checkout_stg_europe_west4_dataflow.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_shop_dp_stg_0.number}@compute-system.iam.gserviceaccount.com"
}

# BigQuery datasets and tables
resource "google_kms_crypto_key" "app_checkout_stg_europe_west4_bigquery" {
  name            = "bigquery"
  key_ring        = google_kms_key_ring.app_checkout_stg_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_checkout_stg_europe_west4_bigquery_shop_dp_stg_0_1" {
  crypto_key_id = google_kms_crypto_key.app_checkout_stg_europe_west4_bigquery.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:bq-${data.google_project.project_shop_dp_stg_0.number}@bigquery-encryption.iam.gserviceaccount.com"
}

# The service agent's address contains the project number, which is not the
# project id and is not known until the project exists.
data "google_project" "project_shop_dp_stg_0" {
  project_id = local.project_shop_dp_stg_0
}




# --- Runtime identity: checkout-api-stg -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-checkout-api-stg" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_shop_app_stg_0
  name        = "checkout-api-stg"
  description = "Runtime identity for api (stg)"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}


# --- Runtime identity: checkout-stream-processing-stg -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-checkout-stream-processing-stg" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_shop_dp_stg_0
  name        = "checkout-stream-processing-stg"
  description = "Runtime identity for stream-processing (stg)"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}

# --- What delivery may do here ------------------------------------------
# The delivery pipeline deploys as checkout-deploy, which the
# delivery stage creates in the central project. It can deploy into this
# environment because this environment's stage says so -- not because the
# delivery identity holds a role here, which would make one identity able to
# change every environment.
resource "google_project_iam_member" "delivery-deploys-into-stg" {
  project = local.project_shop_app_stg_0
  role    = "roles/run.developer"
  member  = "serviceAccount:checkout-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# A release runs as checkout-api-stg, and whoever deploys it has to be allowed to
# say so.
resource "google_service_account_iam_member" "delivery-acts-as-checkout-api-stg" {
  service_account_id = module.sa-checkout-api-stg.id
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:checkout-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# --- Front door: checkout-internet-stg -----------------------------------------
# The only way in. checkout-api-stg accepts traffic from this load
# balancer and nothing else, so a request that skips the firewall policy has
# nowhere to arrive.
module "lb-checkout-internet-stg" {
  source     = "../../../modules/net-lb-app-ext"
  project_id = local.project_shop_app_stg_0
  name       = "checkout-internet-stg"
  protocol = "HTTPS"
  ssl_certificates = {
    managed_configs = {
      default = {
        # A placeholder until you own the name. The certificate stays
        # PROVISIONING until this domain resolves to the address below, which
        # the preflight checks and the README explains.
        domains = ["checkout-stg.example.com"]
      }
    }
  }

  # A serverless endpoint group is how a load balancer reaches Cloud Run:
  # there is no instance to put in a backend.
  neg_configs = {
    default = {
      cloudrun = {
        region         = "europe-west4"
        target_service = { name = "checkout-api-stg" }
      }
    }
  }

  backend_service_configs = {
    default = {
      backends = [{ group = "default" }]
      # The landing zone's own policy, attached by name. This layer never
      # writes rule content: that belongs to the Security page.
      security_policy = "compliance-waf-policy"
      log_config = {
        enable      = true
        sample_rate = 1
      }
    }
  }

  labels = {
    application = "checkout"
    environment = "stg"
    managed-by  = "merlin"
  }
}

# --- Cloud Run service: checkout-api-stg -------------------------------
module "run-checkout-api-stg" {
  source     = "../../../modules/cloud-run-v2"
  project_id = local.project_shop_app_stg_0
  name       = "checkout-api-stg"
  region     = "europe-west4"
  containers = {
    app = {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
      resources = {
        limits = {
          cpu    = "1"
          memory = "512Mi"
        }
      }
    }
  }
  service_config = {
    ingress = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
    max_concurrency = 80
    scaling = {
      min_instance_count = 1
      max_instance_count = 50
    }
  }
  revision = {
    timeout = "300s"
    vpc_access = {
      network = var.vpc_self_links["vpc-shared-dev"]
      subnet  = var.subnet_self_links["vpc-shared-dev"]["europe-west4/sb-shop-stg-europe-west4"]
      egress  = "PRIVATE_RANGES_ONLY"
    }
  }
  service_account_config = {
    # The identity is created above, because the edges of the graph grant to
    # it; the service only attaches to it. Letting the module create its own
    # would give the workload an identity nothing had granted anything.
    create = false
    email  = module.sa-checkout-api-stg.email
  }
  deletion_protection = false
  labels = {
    application = "checkout"
    environment = "stg"
    managed-by  = "merlin"
  }
}

# --- Cloud SQL instance: checkout-relational-stg -----------------------------
# No public address, private connectivity onto this environment's own VPC.
module "sql-checkout-relational-stg" {
  source              = "../../../modules/cloudsql-instance"
  project_id          = local.project_shop_dp_stg_0
  name                = "checkout-relational-stg"
  region              = "europe-west4"
  database_version    = "POSTGRES_15"
  tier                = "db-custom-1-3840"
  availability_type   = "ZONAL"
  network_config = {
    # Private Service Access onto this environment's own VPC: no public
    # IPv4, and no authorized network list to keep correct over time.
    connectivity = {
      public_ipv4 = false
      psa_config = {
        private_network = var.vpc_self_links["vpc-shared-dev"]
      }
    }
  }
  ssl = {
    mode = "ENCRYPTED_ONLY"
  }
  databases = [
    "checkout",
  ]
  encryption_key_name = google_kms_crypto_key.app_checkout_stg_europe_west4_cloudsql.id
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  flags = {
    "cloudsql.enable_pgaudit" = "on"
  }
  # Google's attribute applies on every surface; Terraform's only stops a
  # careless apply. Production sets both.
  gcp_deletion_protection       = false
  terraform_deletion_protection = false
  labels = {
    application = "checkout"
    environment = "stg"
    managed-by  = "merlin"
  }
}

# --- Secret: checkout-db-stg -------------------------------------------
# The container only. The value is added out of band, so it never passes
# through a specification, a bundle or a state file.
module "secret-checkout-db-stg" {
  source     = "../../../modules/secret-manager"
  project_id = local.project_shop_app_stg_0
  secrets = {
    # The accessor is set on the secret itself: the module takes iam per
    # secret, not for the whole project.
    "checkout-db-stg" = {
      iam = {
        "roles/secretmanager.secretAccessor" = [module.sa-checkout-api-stg.iam_email]
      }
    }
  }
}

# --- Bucket: checkout-pipeline-stg -------------------------------------------
# Public access prevention is enforced rather than merely unset: a bucket
# that can be made public later is a bucket that will be.
module "bucket-checkout-pipeline-stg" {
  source                      = "../../../modules/gcs"
  project_id                  = local.project_shop_dp_stg_0
  name                        = "checkout-pipeline-stg"
  location                    = "EUROPE-WEST4"
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
  public_access_prevention    = "enforced"
  versioning                  = false
  force_destroy               = false
  labels = {
    application = "checkout"
    environment = "stg"
    managed-by  = "merlin"
  }
}

# --- Topic: checkout-events-stg ---------------------------------------------
module "topic-checkout-events-stg" {
  source     = "../../../modules/pubsub"
  project_id = local.project_shop_dp_stg_0
  name       = "checkout-events-stg"
  # Messages are stored only where the residency policy allows.
  regions = ["europe-west4"]
  message_retention_duration = "86400s"
  kms_key = google_kms_crypto_key.app_checkout_stg_europe_west4_pubsub.id
  # One subscription per consumer: a topic with none drops every message it
  # receives, which is a silent failure rather than a loud one.
  subscriptions = {
    "stream-processing-stg" = {}
  }
  labels = {
    application = "checkout"
    environment = "stg"
    managed-by  = "merlin"
  }
}

# --- Dataset: checkout_warehouse_stg -----------------------------------------
module "dataset-checkout-warehouse-stg" {
  source     = "../../../modules/bigquery-dataset"
  project_id = local.project_shop_dp_stg_0
  id         = "checkout_warehouse_stg"
  location   = "europe-west4"
  encryption_key = google_kms_crypto_key.app_checkout_stg_europe_west4_bigquery.id
  options = {
    delete_contents_on_destroy = false
  }
  labels = {
    application = "checkout"
    environment = "stg"
    managed-by  = "merlin"
  }
}

# --- Pipeline: checkout-stream-processing-stg ---------------------------------------
# One of Google's provided templates, so the common shape needs no pipeline
# code. Workers run with private addresses and as their own identity, never
# as the project's default Compute Engine account.
resource "google_dataflow_flex_template_job" "checkout-stream-processing-stg" {
  provider                = google-beta
  project                 = local.project_shop_dp_stg_0
  name                    = "checkout-stream-processing-stg"
  region                  = "europe-west4"
  container_spec_gcs_path = "gs://dataflow-templates/latest/flex/PubSub_to_BigQuery_Flex"
  service_account_email   = module.sa-checkout-stream-processing-stg.email
  ip_configuration        = "WORKER_IP_PRIVATE"
  max_workers             = 2
  machine_type            = "n1-standard-2"
  network    = var.vpc_self_links["vpc-shared-dev"]
  subnetwork = var.subnet_self_links["vpc-shared-dev"]["europe-west4/sb-shop-stg-europe-west4"]
  temp_location    = "gs://${module.bucket-checkout-pipeline-stg.name}/temp"
  staging_location = "gs://${module.bucket-checkout-pipeline-stg.name}/staging"
  kms_key_name = google_kms_crypto_key.app_checkout_stg_europe_west4_dataflow.id
  # The pubsub-to-bigquery template still needs to be told what it
  # is reading and where it is writing. Those are the application's to fill in.
  parameters = {
    # inputSubscription = ""
    # outputTableSpec = ""
  }
  labels = {
    application = "checkout"
    environment = "stg"
    managed-by  = "merlin"
  }
  lifecycle {
    ignore_changes = [parameters, labels]
  }
}

# --- Grants that land on one resource ------------------------------------
# Each names the edge that produced it. A role with a resource-scoped form is
# never widened to the project: that is what makes the least-privilege claim
# in CONFORMANCE.md checkable rather than decorative.
resource "google_pubsub_topic_iam_member" "checkout-api-stg-roles-pubsub-publisher-checkout-events-stg" {
  # api -> events
  project = local.project_shop_dp_stg_0
  topic = module.topic-checkout-events-stg.id
  role   = "roles/pubsub.publisher"
  member = module.sa-checkout-api-stg.iam_email
}
resource "google_pubsub_topic_iam_member" "checkout-stream-processing-stg-roles-pubsub-subscriber-checkout-events-stg" {
  # events -> stream-processing
  project = local.project_shop_dp_stg_0
  topic = module.topic-checkout-events-stg.id
  role   = "roles/pubsub.subscriber"
  member = module.sa-checkout-stream-processing-stg.iam_email
}
resource "google_pubsub_topic_iam_member" "checkout-stream-processing-stg-roles-pubsub-viewer-checkout-events-stg" {
  # events -> stream-processing
  project = local.project_shop_dp_stg_0
  topic = module.topic-checkout-events-stg.id
  role   = "roles/pubsub.viewer"
  member = module.sa-checkout-stream-processing-stg.iam_email
}
resource "google_storage_bucket_iam_member" "checkout-stream-processing-stg-roles-storage-objectadmin-checkout-pipeline-stg" {
  # events -> stream-processing
  bucket = module.bucket-checkout-pipeline-stg.name
  role   = "roles/storage.objectAdmin"
  member = module.sa-checkout-stream-processing-stg.iam_email
}
resource "google_bigquery_dataset_iam_member" "checkout-stream-processing-stg-roles-bigquery-dataeditor-checkout-warehouse-stg" {
  # stream-processing -> warehouse
  project = local.project_shop_dp_stg_0
  dataset_id = module.dataset-checkout-warehouse-stg.dataset_id
  role   = "roles/bigquery.dataEditor"
  member = module.sa-checkout-stream-processing-stg.iam_email
}

# --- Grants the edges of the graph imply ---------------------------------
# Each binding names the edge that produced it. A role that no edge can
# account for is a defect, and the least-privilege gate fails on it.
resource "google_project_iam_member" "checkout-api-stg-roles-cloudsql-client-checkout-relational-stg" {
  # api -> relational -- project-scoped because Cloud SQL exposes no resource-level IAM: `cloudsql.client` can only be granted on the project that holds the instance. That data project holds the instances of every application in the environment, so the binding carries an IAM condition on this instance's resource name; without it the identity could connect to all of them (P7).
  project = local.project_shop_dp_stg_0
  role    = "roles/cloudsql.client"
  member  = module.sa-checkout-api-stg.iam_email
  condition {
    title      = "only checkout-relational-stg"
    expression = "resource.name == 'projects/${local.project_shop_dp_stg_0}/instances/${module.sql-checkout-relational-stg.name}' && resource.service == 'sqladmin.googleapis.com'"
  }
}
resource "google_project_iam_member" "checkout-api-stg-roles-cloudsql-instanceuser-checkout-relational-stg" {
  # api -> relational -- project-scoped because Cloud SQL exposes no resource-level IAM: `cloudsql.client` can only be granted on the project that holds the instance. That data project holds the instances of every application in the environment, so the binding carries an IAM condition on this instance's resource name; without it the identity could connect to all of them (P7).
  project = local.project_shop_dp_stg_0
  role    = "roles/cloudsql.instanceUser"
  member  = module.sa-checkout-api-stg.iam_email
  condition {
    title      = "only checkout-relational-stg"
    expression = "resource.name == 'projects/${local.project_shop_dp_stg_0}/instances/${module.sql-checkout-relational-stg.name}' && resource.service == 'sqladmin.googleapis.com'"
  }
}
resource "google_project_iam_member" "checkout-stream-processing-stg-roles-dataflow-worker-shop-dp-stg-0" {
  # events -> stream-processing -- project-scoped because roles/dataflow.worker is granted on a project; Dataflow has no per-job IAM.
  project = local.project_shop_dp_stg_0
  role    = "roles/dataflow.worker"
  member  = module.sa-checkout-stream-processing-stg.iam_email
}
resource "google_project_iam_member" "checkout-stream-processing-stg-roles-bigquery-jobuser-shop-dp-stg-0" {
  # stream-processing -> warehouse -- project-scoped because Running a load job is a project-level permission in BigQuery: there is no dataset-scoped equivalent of `bigquery.jobUser`.
  project = local.project_shop_dp_stg_0
  role    = "roles/bigquery.jobUser"
  member  = module.sa-checkout-stream-processing-stg.iam_email
}
