# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// Outputs of 3-app-checkout-stg, for the pipeline that deploys into it.

output "application" {
  description = "The application this stage belongs to."
  value       = "checkout"
}

output "environment" {
  description = "The environment this stage builds."
  value       = "stg"
}

output "service_accounts" {
  description = "Runtime identities, by node. Deploy as these, never as a key."
  value = {
    "api" = module.sa-checkout-api-stg.email
    "stream-processing" = module.sa-checkout-stream-processing-stg.email
  }
}

output "service_urls" {
  description = "Cloud Run service URLs. Reachable through the front door, not directly."
  value = {
    "checkout-api-stg" = module.run-checkout-api-stg.service_uri
  }
}

output "database_connection_names" {
  description = "Cloud SQL connection names, for the application's own configuration."
  value = {
    "checkout-relational-stg" = module.sql-checkout-relational-stg.connection_name
  }
  sensitive = false
}
