# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Pre-filled from the landing zone: the on-premises ranges its hybrid
# connection routes to (2-networking). Keep only the ones administrators
# reach the control plane from, and add any other.
corporate_ranges = {
  "onprem-1" = "10.20.0.0/16"
}
