# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-gke-stg — GKE clusters for the "stg" environment.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Reads the FAST outputs of 0-org-setup (project ids, principals, KMS keys)
# and 2-networking (VPC / subnet self links) and instantiates the Fabric GKE
# modules for every cluster declared under clusters/ and nodepools/.
# The YAML files next to this root are the readable inventory of the same
# definitions; edit them together.

locals {
  project_id = lookup(var.project_ids, "gke-stg-0", "${var.prefix}-gke-stg-0")
}

# Placeholder: the corporate ranges allowed to reach the control plane.
variable "corporate_ranges" {
  description = "Name => CIDR of the networks administrators reach the cluster control plane from. Pre-filled in corporate.auto.tfvars where the landing zone routes to on-premises ranges."
  type        = map(string)
  nullable    = false
  validation {
    condition = length(var.corporate_ranges) > 0 && alltrue([
      for cidr in values(var.corporate_ranges) : can(cidrhost(cidr, 0))
    ])
    error_message = "Supply at least one range, each a valid CIDR."
  }
}

# --- cluster: gke-stg (standard) ---------------------------------------
module "cluster-gke-stg" {
  source     = "../../../modules/gke-cluster-standard"
  project_id = local.project_id
  name       = "gke-stg"
  location   = "europe-west4"
  vpc_config = {
    network    = var.vpc_self_links["vpc-shared-dev"]
    subnetwork = var.subnet_self_links["vpc-shared-dev"]["europe-west4/sb-stg-europe-west4"]
    secondary_range_names = {
      pods     = "pods"
      services = "services"
    }
  }
  access_config = {
    private_nodes = true
    ip_access = {
      disable_public_endpoint = true
      authorized_ranges       = var.corporate_ranges
    }
  }
  release_channel = "REGULAR"
  enable_features = {
    workload_identity    = true
    dataplane_v2         = true
    binary_authorization = false
    database_encryption = {
      state    = "ENCRYPTED"
      key_name = var.kms_keys["gke-kr-europe-west4"]
    }
  }
  maintenance_config = {
    recurring_window = {
      start_time = "2026-01-01T03:00:00Z"
      end_time   = "2026-01-01T07:00:00Z"
      recurrence = "FREQ=WEEKLY;BYDAY=SA,SU"
    }
  }
  labels = {
    environment = "stg"
    managed-by  = "merlin"
  }
  deletion_protection = false
}

module "nodepool-gke-stg-gke-prod-pool" {
  source       = "../../../modules/gke-nodepool"
  project_id   = local.project_id
  cluster_name = module.cluster-gke-stg.name
  location     = "europe-west4"
  name         = "gke-prod-pool"
  node_config = {
    machine_type = "e2-standard-4"
    disk_size_gb = 100
    disk_type    = "pd-balanced"
  }
  nodepool_config = {
    autoscaling = {
      min_node_count = 1
      max_node_count = 3
    }
  }
}
