# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

output "project_id" {
  description = "GKE project for this environment."
  value       = local.project_id
}

output "clusters" {
  description = "Cluster ids and endpoints."
  value = {
    "gke-stg" = {
      id       = module.cluster-gke-stg.id
      endpoint = module.cluster-gke-stg.endpoint
      location = "europe-west4"
    }
  }
}
