# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# FAST stage-3 input contract (matches fast/stages/3-*/variables-fast.tf in
# Cloud Foundation Fabric v58.0.0) plus the 2-networking outputs.
# Values arrive through the tfvars files the earlier stages publish to the
# iac-outputs bucket (0-org-setup.auto.tfvars.json, 2-networking.auto.tfvars.json,
# 2-security.auto.tfvars.json) — fetch them with fast-links.sh.

variable "automation" {
  description = "Automation resources created by the bootstrap stage."
  type = object({
    outputs_bucket = string
  })
  nullable = false
}

variable "billing_account" {
  description = "Billing account id."
  type = object({
    id = optional(string)
  })
  default = {}
}

variable "custom_roles" {
  description = "Custom roles defined at the org level, in key => id format."
  type        = map(string)
  nullable    = false
  default     = {}
}

variable "folder_ids" {
  description = "Folders created in the bootstrap stage."
  type        = map(string)
  nullable    = false
  default     = {}
}

variable "iam_principals" {
  description = "IAM-format principals."
  type        = map(string)
  nullable    = false
  default     = {}
}

variable "kms_keys" {
  description = "KMS key ids from 2-security, in <key>-<keyring> => id format."
  type        = map(string)
  nullable    = false
  default     = {}
}

variable "prefix" {
  description = "Prefix for organization projects."
  type        = string
  nullable    = false
}

variable "project_ids" {
  description = "Projects created in the bootstrap stage (project-factory ids are derived from the prefix)."
  type        = map(string)
  nullable    = false
  default     = {}
}

variable "host_project_ids" {
  description = "Shared VPC host project ids from 2-networking."
  type        = map(string)
  nullable    = false
  default     = {}
}

variable "vpc_self_links" {
  description = "VPC self links from 2-networking, keyed by VPC."
  type        = map(string)
  nullable    = false
}

variable "subnet_self_links" {
  description = "Subnet self links from 2-networking, keyed by VPC then <region>/<subnet>."
  type        = map(map(string))
  nullable    = false
}
