# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Stage 3-app-storefront-dev -- the "storefront" application in dev.
# Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
# Archetype K1: Microservices on the shared cluster.
#
# Everything below was derived from the archetype's graph and the landing zone
# this application is compiled against. Each identity exists because a compute
# node runs as it; each binding exists because an edge of the graph needs it.
# CONFORMANCE.md in this bundle says which edge produced which grant, and which
# rule produced each setting.

locals {
  # Every resource in shop-app-dev-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_shop_app_dev_0 = one(distinct(concat(
    [for s in google_project_service.shop_app_dev_0 : s.project],
    [for s in google_project_service_identity.shop_app_dev_0 : s.project],
  )))
  project_gke_dev_0 = lookup(var.project_ids, "gke-dev-0", "${var.prefix}-gke-dev-0")
  # Every resource in shop-dp-dev-0 reads this name, so every one of them
  # waits for the services below to be enabled first.
  project_shop_dp_dev_0 = one(distinct(concat(
    [for s in google_project_service.shop_dp_dev_0 : s.project],
    [for s in google_project_service_identity.shop_dp_dev_0 : s.project],
  )))
  project_sec_core_0 = lookup(var.project_ids, "sec-core-0", "${var.prefix}-sec-core-0")
  project_app_core_0 = lookup(var.project_ids, "app-core-0", "${var.prefix}-app-core-0")
}

# --- Services this stage enables in shop-app-dev-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "shop_app_dev_0" {
  for_each = toset([
    "iam.googleapis.com",
    "secretmanager.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "shop-app-dev-0", "${var.prefix}-shop-app-dev-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "shop_app_dev_0" {
  provider = google-beta
  for_each = toset([
    "secretmanager.googleapis.com",
  ])
  project = google_project_service.shop_app_dev_0[each.key].project
  service = each.key
}

# --- Services this stage enables in shop-dp-dev-0 -------------------------
# The landing zone enables what its own projects use and cannot know what an
# application brings. This stage uses these and the landing zone does not
# enable them, so it does -- and never disables them on destroy, because
# another stage in the same project may use them by then.
resource "google_project_service" "shop_dp_dev_0" {
  for_each = toset([
    "pubsub.googleapis.com",
    "redis.googleapis.com",
    "sqladmin.googleapis.com",
  ])
  project                    = lookup(var.project_ids, "shop-dp-dev-0", "${var.prefix}-shop-dp-dev-0")
  service                    = each.key
  disable_on_destroy         = false
  disable_dependent_services = false
}

# The service's own agent, created now rather than on first use: a key or a
# role granted to an agent that does not exist yet fails at apply.
resource "google_project_service_identity" "shop_dp_dev_0" {
  provider = google-beta
  for_each = toset([
    "pubsub.googleapis.com",
    "redis.googleapis.com",
    "sqladmin.googleapis.com",
  ])
  project = google_project_service.shop_dp_dev_0[each.key].project
  service = each.key
}


# --- Keys this stage owns -------------------------------------------------
# A framework in force requires customer-managed encryption and the landing
# zone wired no key into these projects for these services -- it wires one
# for each service a project already enables, and an application introduces
# services the landing zone never heard of.
#
# The keys live in the landing zone's key project, beside the keys it made --
# the people who hold keys are not the people who hold the data -- in a
# keyring this application owns, never the landing zone's own. Each is in
# the location of the resource it encrypts, because a key is only usable
# from there. Rotation is the shortest period any framework in force asks for.
#
# Where the landing zone wires a key for a service, this stage uses that one
# and creates none: enable the service on the Security page and regenerate
# the landing zone to move a key there.
resource "google_kms_key_ring" "app_storefront_dev_europe_west4" {
  project  = local.project_sec_core_0
  name     = "app-storefront-dev-europe-west4"
  location = "europe-west4"
}

# Cloud SQL instances
resource "google_kms_crypto_key" "app_storefront_dev_europe_west4_cloudsql" {
  name            = "cloudsql"
  key_ring        = google_kms_key_ring.app_storefront_dev_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_storefront_dev_europe_west4_cloudsql_shop_dp_dev_0_1" {
  crypto_key_id = google_kms_crypto_key.app_storefront_dev_europe_west4_cloudsql.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_shop_dp_dev_0.number}@gcp-sa-cloud-sql.iam.gserviceaccount.com"
}

# Pub/Sub message encryption
resource "google_kms_crypto_key" "app_storefront_dev_europe_west4_pubsub" {
  name            = "pubsub"
  key_ring        = google_kms_key_ring.app_storefront_dev_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_storefront_dev_europe_west4_pubsub_shop_dp_dev_0_1" {
  crypto_key_id = google_kms_crypto_key.app_storefront_dev_europe_west4_pubsub.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_shop_dp_dev_0.number}@gcp-sa-pubsub.iam.gserviceaccount.com"
}

# Memorystore for Redis persistence and backups
resource "google_kms_crypto_key" "app_storefront_dev_europe_west4_memorystore" {
  name            = "memorystore"
  key_ring        = google_kms_key_ring.app_storefront_dev_europe_west4.id
  rotation_period = "7776000s"   # 90 days

  # A key that can be deleted while something is encrypted with it takes the
  # data with it.
  lifecycle {
    prevent_destroy = true
  }
}

# The service encrypts with its own agent, not with yours. Without this
# grant the resource below does not fail to be encrypted -- it fails to be
# created, which reads as a permissions problem somewhere else entirely.
resource "google_kms_crypto_key_iam_member" "app_storefront_dev_europe_west4_memorystore_shop_dp_dev_0_1" {
  crypto_key_id = google_kms_crypto_key.app_storefront_dev_europe_west4_memorystore.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.project_shop_dp_dev_0.number}@cloud-redis.iam.gserviceaccount.com"
}

# The service agent's address contains the project number, which is not the
# project id and is not known until the project exists.
data "google_project" "project_shop_dp_dev_0" {
  project_id = local.project_shop_dp_dev_0
}




# --- Runtime identity: storefront-services-dev -------------------------------
# Created before anything grants to it: a binding that arrives first is a
# plan-time error the customer would have to debug.
module "sa-storefront-services-dev" {
  source     = "../../../modules/iam-service-account"
  project_id = local.project_shop_app_dev_0
  name        = "storefront-services-dev"
  description = "Runtime identity for services (dev), reached from the cluster through Workload Identity"
  # The module creates the account and no key with it: the workload
  # authenticates as itself, so there is no credential to leak or rotate.
}

# --- What delivery may do here ------------------------------------------
# The delivery pipeline deploys as storefront-deploy, which the
# delivery stage creates in the central project. It can deploy into this
# environment because this environment's stage says so -- not because the
# delivery identity holds a role here, which would make one identity able to
# change every environment.
resource "google_project_iam_member" "delivery-deploys-into-dev" {
  project = local.project_gke_dev_0
  role    = "roles/container.developer"
  member  = "serviceAccount:storefront-deploy@${local.project_app_core_0}.iam.gserviceaccount.com"
}

# --- Cache: storefront-cache-dev ---------------------------------------------
# Private services access from this environment's own VPC, with AUTH on: a
# cache on a private network with no authentication is readable by anything
# else on that network, which is the whole VPC.
resource "google_redis_instance" "storefront-cache-dev" {
  project        = local.project_shop_dp_dev_0
  name           = "storefront-cache-dev"
  region         = "europe-west4"
  tier           = "BASIC"
  memory_size_gb = 1
  redis_version  = "REDIS_7_0"

  connect_mode            = "PRIVATE_SERVICE_ACCESS"
  authorized_network      = var.vpc_self_links["vpc-shared-dev"]
  auth_enabled            = true
  transit_encryption_mode = "SERVER_AUTHENTICATION"
  customer_managed_key = google_kms_crypto_key.app_storefront_dev_europe_west4_memorystore.id

  labels = {
    application = "storefront"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Cloud SQL instance: storefront-relational-dev -----------------------------
# No public address, private connectivity onto this environment's own VPC.
module "sql-storefront-relational-dev" {
  source              = "../../../modules/cloudsql-instance"
  project_id          = local.project_shop_dp_dev_0
  name                = "storefront-relational-dev"
  region              = "europe-west4"
  database_version    = "POSTGRES_15"
  tier                = "db-custom-1-3840"
  availability_type   = "ZONAL"
  network_config = {
    # Private Service Access onto this environment's own VPC: no public
    # IPv4, and no authorized network list to keep correct over time.
    connectivity = {
      public_ipv4 = false
      psa_config = {
        private_network = var.vpc_self_links["vpc-shared-dev"]
      }
    }
  }
  ssl = {
    mode = "ENCRYPTED_ONLY"
  }
  databases = [
    "storefront",
  ]
  encryption_key_name = google_kms_crypto_key.app_storefront_dev_europe_west4_cloudsql.id
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  flags = {
    "cloudsql.enable_pgaudit" = "on"
  }
  # Google's attribute applies on every surface; Terraform's only stops a
  # careless apply. Production sets both.
  gcp_deletion_protection       = false
  terraform_deletion_protection = false
  labels = {
    application = "storefront"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Secret: storefront-db-dev -------------------------------------------
# The container only. The value is added out of band, so it never passes
# through a specification, a bundle or a state file.
module "secret-storefront-db-dev" {
  source     = "../../../modules/secret-manager"
  project_id = local.project_shop_app_dev_0
  secrets = {
    # The accessor is set on the secret itself: the module takes iam per
    # secret, not for the whole project.
    "storefront-db-dev" = {
      iam = {
        "roles/secretmanager.secretAccessor" = [module.sa-storefront-services-dev.iam_email]
      }
    }
  }
}

# --- Workload Identity: storefront-services-dev ------------------------------
# The Kubernetes account in manifests.yaml impersonates this Google one, so
# every grant in this file lands on a Google identity and no key is ever
# written into a secret. Apply this before the manifests: a pod that
# authenticates as an identity nobody created gets a permission error nobody
# can explain.
resource "google_service_account_iam_member" "storefront-services-dev-workload-identity" {
  service_account_id = module.sa-storefront-services-dev.id
  role               = "roles/iam.workloadIdentityUser"
  member             = "serviceAccount:${local.project_gke_dev_0}.svc.id.goog[storefront-dev/storefront-services-dev]"
}

# --- Topic: storefront-events-dev ---------------------------------------------
module "topic-storefront-events-dev" {
  source     = "../../../modules/pubsub"
  project_id = local.project_shop_dp_dev_0
  name       = "storefront-events-dev"
  # Messages are stored only where the residency policy allows.
  regions = ["europe-west4"]
  message_retention_duration = "86400s"
  kms_key = google_kms_crypto_key.app_storefront_dev_europe_west4_pubsub.id
  labels = {
    application = "storefront"
    environment = "dev"
    managed-by  = "merlin"
  }
}

# --- Grants that land on one resource ------------------------------------
# Each names the edge that produced it. A role with a resource-scoped form is
# never widened to the project: that is what makes the least-privilege claim
# in CONFORMANCE.md checkable rather than decorative.
resource "google_pubsub_topic_iam_member" "storefront-services-dev-roles-pubsub-publisher-storefront-events-dev" {
  # services -> events
  project = local.project_shop_dp_dev_0
  topic = module.topic-storefront-events-dev.id
  role   = "roles/pubsub.publisher"
  member = module.sa-storefront-services-dev.iam_email
}

# --- Grants the edges of the graph imply ---------------------------------
# Each binding names the edge that produced it. A role that no edge can
# account for is a defect, and the least-privilege gate fails on it.
resource "google_project_iam_member" "storefront-services-dev-roles-cloudsql-client-storefront-relational-dev" {
  # services -> relational -- project-scoped because Cloud SQL exposes no resource-level IAM: `cloudsql.client` can only be granted on the project that holds the instance. That data project holds the instances of every application in the environment, so the binding carries an IAM condition on this instance's resource name; without it the identity could connect to all of them (P7).
  project = local.project_shop_dp_dev_0
  role    = "roles/cloudsql.client"
  member  = module.sa-storefront-services-dev.iam_email
  condition {
    title      = "only storefront-relational-dev"
    expression = "resource.name == 'projects/${local.project_shop_dp_dev_0}/instances/${module.sql-storefront-relational-dev.name}' && resource.service == 'sqladmin.googleapis.com'"
  }
}
resource "google_project_iam_member" "storefront-services-dev-roles-cloudsql-instanceuser-storefront-relational-dev" {
  # services -> relational -- project-scoped because Cloud SQL exposes no resource-level IAM: `cloudsql.client` can only be granted on the project that holds the instance. That data project holds the instances of every application in the environment, so the binding carries an IAM condition on this instance's resource name; without it the identity could connect to all of them (P7).
  project = local.project_shop_dp_dev_0
  role    = "roles/cloudsql.instanceUser"
  member  = module.sa-storefront-services-dev.iam_email
  condition {
    title      = "only storefront-relational-dev"
    expression = "resource.name == 'projects/${local.project_shop_dp_dev_0}/instances/${module.sql-storefront-relational-dev.name}' && resource.service == 'sqladmin.googleapis.com'"
  }
}
resource "google_project_iam_member" "storefront-services-dev-roles-redis-viewer-storefront-cache-dev" {
  # services -> cache -- project-scoped because Memorystore exposes no resource-level IAM: `redis.viewer` can only be granted on the project that holds the instance. That data project holds the caches of every application in the environment, and the grant covers all of them.
  project = local.project_shop_dp_dev_0
  role    = "roles/redis.viewer"
  member  = module.sa-storefront-services-dev.iam_email
}
