#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Apply the workload stages, in order. Generated by Merlin Studio for
# Cloud Foundation Fabric v58.0.0.
#
#   ./deploy/apply.sh /path/to/fabric-checkout               # plan, then apply
#   ./deploy/apply.sh /path/to/fabric-checkout --plan-only   # plan only
#   ./deploy/apply.sh /path/to/fabric-checkout --env dev     # one environment
#   ./deploy/apply.sh /path/to/fabric-checkout --stage 3-gke-dev
#
# Merlin does not apply anything itself. This is the same sequence written
# out, so it can be read, edited, or replaced by your own pipeline.
set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAST_DIR="${1:-${FAST_CHECKOUT:-}}"
shift || true

PLAN_ONLY=0
ONLY_ENV=""
ONLY_STAGE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --plan-only) PLAN_ONLY=1 ;;
    --env)   ONLY_ENV="${2:-}"; shift ;;
    --stage) ONLY_STAGE="${2:-}"; shift ;;
    *) printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
  shift
done

if [ -z "${FAST_DIR}" ] || [ ! -d "${FAST_DIR}" ]; then
  printf 'usage: ./deploy/apply.sh /path/to/fabric-checkout [--plan-only] [--env CODE] [--stage NAME]\n' >&2
  exit 2
fi

# shellcheck source=/dev/null
source "${BUNDLE_DIR}/deploy/stages.env"

# The landing zone has to be the one these workloads were compiled against.
"${BUNDLE_DIR}/deploy/verify.sh" "${FAST_DIR}"

STAGES_DIR="${FAST_DIR}/fast/stages"
[ -d "${STAGES_DIR}" ] || STAGES_DIR="${FAST_DIR}"

apply_root() {
  local stage="$1" state_prefix="$2" dest="${STAGES_DIR}/$1"
  printf '\n=== %s\n' "${stage}"
  mkdir -p "${dest}"
  cp -r "${BUNDLE_DIR}/${stage}/." "${dest}/"
  ( cd "${dest}"
    if [ -n "${state_prefix}" ]; then
      # Every application stage of an environment shares that environment's
      # provider file; its state lives under the file's folder, in its own
      # prefix, so two applications never write the same state.
      terraform init -input=false -backend-config="prefix=${state_prefix}"
    else
      terraform init -input=false
    fi
    terraform plan -input=false -out=tfplan
    if [ "${PLAN_ONLY}" -eq 0 ]; then
      terraform apply -input=false tfplan
    fi )
}

apply_dataset() {
  # Not a Terraform root: the project factory runs against it, with its own
  # state prefix and deploy identity.
  local stage="$1" dataset="$2"
  local pf="${STAGES_DIR}/2-project-factory"
  printf '\n=== %s (project-factory dataset)\n' "${stage}"
  if [ ! -d "${pf}" ]; then
    printf 'no 2-project-factory stage at %s\n' "${pf}" >&2
    exit 1
  fi
  mkdir -p "${pf}/datasets/${dataset}"
  cp -r "${BUNDLE_DIR}/${stage}/." "${pf}/datasets/${dataset}/"
  ( cd "${pf}"
    terraform init -input=false
    terraform plan -input=false -var-file="datasets/${dataset}/terraform.tfvars" -out=tfplan
    if [ "${PLAN_ONLY}" -eq 0 ]; then
      terraform apply -input=false tfplan
    fi )
}

while IFS='|' read -r stage kind environment dataset identity state_prefix; do
  [ -n "${stage}" ] || continue
  [ -z "${ONLY_STAGE}" ] || [ "${ONLY_STAGE}" = "${stage}" ] || continue
  [ -z "${ONLY_ENV}" ] || [ "${ONLY_ENV}" = "${environment}" ] || continue
  # Each stage runs as the identity the landing zone provisioned for it, so
  # a dev stage can never reach production state.
  printf '\n--- %s deploys as %s\n' "${stage}" "${identity}"
  if [ "${kind}" = "dataset" ]; then
    apply_dataset "${stage}" "${dataset}"
  else
    apply_root "${stage}" "${state_prefix}"
  fi
done <<< "${MERLIN_STAGES}"

printf '\n'
if [ "${PLAN_ONLY}" -eq 1 ]; then
  printf 'planned only; nothing was applied\n'
else
  printf 'all stages applied\n'
fi
