#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Preflight for the "seller-assistant" application in dev.
# Generated by Merlin Studio. Nothing here leaves your environment.
#
#   ./deploy/preflight-seller-assistant-dev.sh [PROJECT_OVERRIDE]
#
# Every check below is an assumption the 3-app-seller-assistant-dev stage makes about your
# landing zone. Merlin never read your environment, so this is where those
# assumptions are tested -- before Terraform runs, not during.
set -uo pipefail

fail=0
ok()   { printf 'OK   %s\n' "$*"; }
bad()  { printf 'FAIL %s\n' "$*"; fail=1; }
note() { printf '     %s\n' "$*"; }

if ! command -v gcloud >/dev/null 2>&1; then
  printf 'gcloud is not on PATH; this check needs it.\n'
  exit 2
fi

printf '\nPreflight: seller-assistant (dev)\n'

printf '\nProjects\n'
if gcloud projects describe "vd-seller-app-dev-0" >/dev/null 2>&1; then
  ok "project vd-seller-app-dev-0 exists"
else
  bad "project vd-seller-app-dev-0 does not exist"
  note "the api, embeddings, internet, llm of this application is created in it"
fi
if gcloud projects describe "vd-seller-dp-dev-0" >/dev/null 2>&1; then
  ok "project vd-seller-dp-dev-0 exists"
else
  bad "project vd-seller-dp-dev-0 does not exist"
  note "the events, objects, vectors of this application is created in it"
fi
printf '\nNetwork\n'
if gcloud compute networks describe "vpc-shared-dev" --project="vd-net-core-0" >/dev/null 2>&1; then
  ok "VPC vpc-shared-dev exists in vd-net-core-0"
else
  bad "VPC vpc-shared-dev does not exist in vd-net-core-0"
  note "the api -> vectors, embeddings -> vectors, events -> embeddings, objects -> embeddings paths need it"
fi
if gcloud compute networks subnets describe "sb-seller-dev-europe-west4" \
     --region="europe-west4" --project="vd-net-core-0" >/dev/null 2>&1; then
  ok "subnet sb-seller-dev-europe-west4 exists"
else
  bad "subnet sb-seller-dev-europe-west4 does not exist in europe-west4"
  note "the stage's services reach the private network through it"
fi
printf '\nShared VPC\n'
if [ "$(gcloud compute shared-vpc get-host-project "vd-seller-app-dev-0" \
     --format="value(name)" 2>/dev/null)" = "vd-net-core-0" ]; then
  ok "vd-seller-app-dev-0 is attached to vd-net-core-0"
else
  bad "vd-seller-app-dev-0 is not attached to the Shared VPC host vd-net-core-0"
  note "nothing in it can use the host's subnets; 2-project-factory attaches it"
fi
printf '\nWeb application firewall\n'
if gcloud compute security-policies describe "compliance-waf-policy" \
     --project="vd-seller-app-dev-0" >/dev/null 2>&1; then
  ok "Cloud Armor policy compliance-waf-policy exists in vd-seller-app-dev-0"
else
  bad "Cloud Armor policy compliance-waf-policy not found in vd-seller-app-dev-0"
  note "seller-assistant-internet-dev attaches it; 2-security-edge creates it"
fi
printf '\nModel Armor endpoint\n'
if gcloud dns record-sets describe "modelarmor.europe-west4.rep.googleapis.com." --type=A \
     --zone="modelarmor-vpc-shared-dev-europe-west4" --project="vd-net-core-0" >/dev/null 2>&1; then
  ok "modelarmor.europe-west4.rep.googleapis.com. resolves to a Private Service Connect endpoint on vpc-shared-dev"
else
  bad "no Private Service Connect endpoint for Model Armor in europe-west4 on vpc-shared-dev"
  note "seller-assistant-llm-dev is called through it from the VPC; 2-networking-endpoints creates it"
fi
printf '\nEnabled services\n'
if gcloud services list --enabled --project="vd-sec-core-0" \
     --filter="config.name=cloudkms.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "cloudkms.googleapis.com is enabled in vd-sec-core-0"
else
  bad "cloudkms.googleapis.com is not enabled in vd-sec-core-0"
  note "the landing zone enables it; re-apply 2-project-factory if this is unexpected"
fi
if gcloud services list --enabled --project="vd-seller-app-dev-0" \
     --filter="config.name=compute.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "compute.googleapis.com is enabled in vd-seller-app-dev-0"
else
  note "compute.googleapis.com is not enabled in vd-seller-app-dev-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-seller-app-dev-0" \
     --filter="config.name=iam.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "iam.googleapis.com is enabled in vd-seller-app-dev-0"
else
  note "iam.googleapis.com is not enabled in vd-seller-app-dev-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-seller-app-dev-0" \
     --filter="config.name=modelarmor.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "modelarmor.googleapis.com is enabled in vd-seller-app-dev-0"
else
  note "modelarmor.googleapis.com is not enabled in vd-seller-app-dev-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-seller-app-dev-0" \
     --filter="config.name=monitoring.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "monitoring.googleapis.com is enabled in vd-seller-app-dev-0"
else
  note "monitoring.googleapis.com is not enabled in vd-seller-app-dev-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-seller-app-dev-0" \
     --filter="config.name=run.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "run.googleapis.com is enabled in vd-seller-app-dev-0"
else
  note "run.googleapis.com is not enabled in vd-seller-app-dev-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-seller-dp-dev-0" \
     --filter="config.name=aiplatform.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "aiplatform.googleapis.com is enabled in vd-seller-dp-dev-0"
else
  note "aiplatform.googleapis.com is not enabled in vd-seller-dp-dev-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-seller-dp-dev-0" \
     --filter="config.name=pubsub.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "pubsub.googleapis.com is enabled in vd-seller-dp-dev-0"
else
  note "pubsub.googleapis.com is not enabled in vd-seller-dp-dev-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-seller-dp-dev-0" \
     --filter="config.name=storage.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "storage.googleapis.com is enabled in vd-seller-dp-dev-0"
else
  note "storage.googleapis.com is not enabled in vd-seller-dp-dev-0 yet; this stage enables it on apply"
fi

printf '\n'
if [ "${fail}" -ne 0 ]; then
  printf 'Preflight failed. Each FAIL above names the assumption and the\n'
  printf 'resource it is about. Fix those before applying %s.\n' "3-app-seller-assistant-dev"
  exit 1
fi
printf 'Preflight passed: every assumption %s makes holds in this environment.\n' "3-app-seller-assistant-dev"
