#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Preflight for 3-delivery-pools. Generated by Merlin Studio. Nothing here leaves
# your environment.
set -uo pipefail

fail=0
ok()   { printf 'OK   %s\n' "$*"; }
bad()  { printf 'FAIL %s\n' "$*"; fail=1; }
note() { printf '     %s\n' "$*"; }

if [ "$(gcloud compute shared-vpc get-host-project "vd-app-core-0" --format="value(name)" 2>/dev/null)" = "vd-net-core-0" ]; then
  ok "vd-app-core-0 is attached to the Shared VPC host vd-net-core-0"
else
  bad "vd-app-core-0 is not attached to the Shared VPC host vd-net-core-0"
  note "Cloud Build peers a pool to a Shared VPC network only from an attached project; 2-project-factory attaches it"
fi
if gcloud projects get-iam-policy "vd-app-core-0" --flatten="bindings[].members" \
     --filter="bindings.role=roles/servicenetworking.serviceAgent AND bindings.members~service-networking" \
     --format="value(bindings.members)" 2>/dev/null | grep -q .; then
  ok "the Service Networking agent of vd-app-core-0 holds roles/servicenetworking.serviceAgent"
else
  bad "the Service Networking agent of vd-app-core-0 does not hold roles/servicenetworking.serviceAgent"
  note "pool creation fails with 'cannot access peered_network config'; 2-project-factory enables Service Networking, which grants it"
fi
if gcloud services vpc-peerings list --network="vpc-shared-dev" --project="vd-net-core-0" \
     --service=servicenetworking.googleapis.com --format="value(peering)" 2>/dev/null | grep -q .; then
  ok "Private Service Access connection on vpc-shared-dev in vd-net-core-0"
else
  bad "no Private Service Access connection on vpc-shared-dev in vd-net-core-0"
  note "deploy-vpc-shared-dev peers through it; 2-networking makes it"
fi
if gcloud services vpc-peerings list --network="vpc-shared-prod" --project="vd-net-core-0" \
     --service=servicenetworking.googleapis.com --format="value(peering)" 2>/dev/null | grep -q .; then
  ok "Private Service Access connection on vpc-shared-prod in vd-net-core-0"
else
  bad "no Private Service Access connection on vpc-shared-prod in vd-net-core-0"
  note "deploy-vpc-shared-prod peers through it; 2-networking makes it"
fi

if [ "$fail" -ne 0 ]; then
  printf 'Preflight failed. Fix the FAIL lines before applying 3-delivery-pools.\n'
  exit 1
fi
printf 'Preflight passed for 3-delivery-pools.\n'
