#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Preflight for 3-gke-stg. Generated by Merlin Studio. Nothing here leaves
# your environment.
#
#   ./deploy/preflight-gke-stg.sh
set -uo pipefail

fail=0
ok()   { printf 'OK   %s\n' "$*"; }
bad()  { printf 'FAIL %s\n' "$*"; fail=1; }
note() { printf '     %s\n' "$*"; }

if gcloud projects describe "vd-gke-stg-0" >/dev/null 2>&1; then
  ok "project vd-gke-stg-0 exists"
else
  bad "project vd-gke-stg-0 does not exist"
  note "2-project-factory creates it"
fi
ranges=$(gcloud compute networks subnets describe "sb-stg-europe-west4" \
  --region="europe-west4" --project="vd-net-core-0" \
  --format="value(secondaryIpRanges[].rangeName)" 2>/dev/null)
for range in "pods" "services"; do
  if printf '%s' "$ranges" | tr ';' '\n' | grep -qx "$range"; then
    ok "secondary range $range exists on sb-stg-europe-west4"
  else
    bad "secondary range $range not found on sb-stg-europe-west4"
    note "gke-stg puts its pods and services there; 2-networking creates it"
  fi
done

# The ranges allowed to reach the control plane: TF_VAR_corporate_ranges,
# or corporate.auto.tfvars beside the stage.
stage_dir="$(dirname "$0")/../3-gke-stg"
source_text="${TF_VAR_corporate_ranges:-}"
if [ -z "$source_text" ] && [ -f "$stage_dir/corporate.auto.tfvars" ]; then
  source_text=$(cat "$stage_dir/corporate.auto.tfvars")
fi
cidrs=$(printf '%s' "$source_text" | grep -Eo '[0-9a-fA-F:.]+/[0-9]+' || true)
if [ -z "$cidrs" ]; then
  bad "no corporate ranges supplied for the control plane"
  note "set TF_VAR_corporate_ranges or write corporate.auto.tfvars; see PLACEHOLDERS.md"
else
  for cidr in $cidrs; do
    if printf '%s' "$cidr" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$|:'; then
      ok "corporate range $cidr"
    else
      bad "corporate range $cidr is not a CIDR"
    fi
  done
fi

if [ "$fail" -ne 0 ]; then
  printf 'Preflight failed. Fix the FAIL lines before applying 3-gke-stg.\n'
  exit 1
fi
printf 'Preflight passed for 3-gke-stg.\n'
