#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Preflight for the "checkout" application in stg.
# Generated by Merlin Studio. Nothing here leaves your environment.
#
#   ./deploy/preflight-checkout-stg.sh [PROJECT_OVERRIDE]
#
# Every check below is an assumption the 3-app-checkout-stg stage makes about your
# landing zone. Merlin never read your environment, so this is where those
# assumptions are tested -- before Terraform runs, not during.
set -uo pipefail

fail=0
ok()   { printf 'OK   %s\n' "$*"; }
bad()  { printf 'FAIL %s\n' "$*"; fail=1; }
note() { printf '     %s\n' "$*"; }

if ! command -v gcloud >/dev/null 2>&1; then
  printf 'gcloud is not on PATH; this check needs it.\n'
  exit 2
fi

printf '\nPreflight: checkout (stg)\n'

printf '\nProjects\n'
if gcloud projects describe "vd-shop-app-stg-0" >/dev/null 2>&1; then
  ok "project vd-shop-app-stg-0 exists"
else
  bad "project vd-shop-app-stg-0 does not exist"
  note "the api, internet, secret of this application is created in it"
fi
if gcloud projects describe "vd-shop-dp-stg-0" >/dev/null 2>&1; then
  ok "project vd-shop-dp-stg-0 exists"
else
  bad "project vd-shop-dp-stg-0 does not exist"
  note "the events, objects, relational, stream-processing, warehouse of this application is created in it"
fi
printf '\nNetwork\n'
if gcloud compute networks describe "vpc-shared-dev" --project="vd-net-core-0" >/dev/null 2>&1; then
  ok "VPC vpc-shared-dev exists in vd-net-core-0"
else
  bad "VPC vpc-shared-dev does not exist in vd-net-core-0"
  note "the api -> relational, events -> stream-processing paths need it"
fi
if gcloud compute networks subnets describe "sb-shop-stg-europe-west4" \
     --region="europe-west4" --project="vd-net-core-0" >/dev/null 2>&1; then
  ok "subnet sb-shop-stg-europe-west4 exists"
else
  bad "subnet sb-shop-stg-europe-west4 does not exist in europe-west4"
  note "the stage's services reach the private network through it"
fi
if gcloud compute addresses list --global --project="vd-net-core-0" \
     --filter="purpose=VPC_PEERING AND network~vpc-shared-dev$ AND name=psa-shared-dev" \
     --format="value(name)" 2>/dev/null | grep -q .; then
  ok "Private Service Access range psa-shared-dev on vpc-shared-dev"
else
  bad "no Private Service Access range psa-shared-dev on vpc-shared-dev"
  note "a private database or cache cannot be created without one; 2-networking reserves it"
fi
printf '\nShared VPC\n'
if [ "$(gcloud compute shared-vpc get-host-project "vd-shop-app-stg-0" \
     --format="value(name)" 2>/dev/null)" = "vd-net-core-0" ]; then
  ok "vd-shop-app-stg-0 is attached to vd-net-core-0"
else
  bad "vd-shop-app-stg-0 is not attached to the Shared VPC host vd-net-core-0"
  note "nothing in it can use the host's subnets; 2-project-factory attaches it"
fi
if [ "$(gcloud compute shared-vpc get-host-project "vd-shop-dp-stg-0" \
     --format="value(name)" 2>/dev/null)" = "vd-net-core-0" ]; then
  ok "vd-shop-dp-stg-0 is attached to vd-net-core-0"
else
  bad "vd-shop-dp-stg-0 is not attached to the Shared VPC host vd-net-core-0"
  note "nothing in it can use the host's subnets; 2-project-factory attaches it"
fi
printf '\nWeb application firewall\n'
if gcloud compute security-policies describe "compliance-waf-policy" \
     --project="vd-shop-app-stg-0" >/dev/null 2>&1; then
  ok "Cloud Armor policy compliance-waf-policy exists in vd-shop-app-stg-0"
else
  bad "Cloud Armor policy compliance-waf-policy not found in vd-shop-app-stg-0"
  note "checkout-internet-stg attaches it; 2-security-edge creates it"
fi
printf '\nEnabled services\n'
if gcloud services list --enabled --project="vd-sec-core-0" \
     --filter="config.name=cloudkms.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "cloudkms.googleapis.com is enabled in vd-sec-core-0"
else
  bad "cloudkms.googleapis.com is not enabled in vd-sec-core-0"
  note "the landing zone enables it; re-apply 2-project-factory if this is unexpected"
fi
if gcloud services list --enabled --project="vd-shop-app-stg-0" \
     --filter="config.name=compute.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "compute.googleapis.com is enabled in vd-shop-app-stg-0"
else
  note "compute.googleapis.com is not enabled in vd-shop-app-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-app-stg-0" \
     --filter="config.name=iam.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "iam.googleapis.com is enabled in vd-shop-app-stg-0"
else
  note "iam.googleapis.com is not enabled in vd-shop-app-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-app-stg-0" \
     --filter="config.name=monitoring.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "monitoring.googleapis.com is enabled in vd-shop-app-stg-0"
else
  note "monitoring.googleapis.com is not enabled in vd-shop-app-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-app-stg-0" \
     --filter="config.name=run.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "run.googleapis.com is enabled in vd-shop-app-stg-0"
else
  note "run.googleapis.com is not enabled in vd-shop-app-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-app-stg-0" \
     --filter="config.name=secretmanager.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "secretmanager.googleapis.com is enabled in vd-shop-app-stg-0"
else
  note "secretmanager.googleapis.com is not enabled in vd-shop-app-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-dp-stg-0" \
     --filter="config.name=bigquery.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "bigquery.googleapis.com is enabled in vd-shop-dp-stg-0"
else
  note "bigquery.googleapis.com is not enabled in vd-shop-dp-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-dp-stg-0" \
     --filter="config.name=dataflow.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "dataflow.googleapis.com is enabled in vd-shop-dp-stg-0"
else
  note "dataflow.googleapis.com is not enabled in vd-shop-dp-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-dp-stg-0" \
     --filter="config.name=iam.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "iam.googleapis.com is enabled in vd-shop-dp-stg-0"
else
  note "iam.googleapis.com is not enabled in vd-shop-dp-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-dp-stg-0" \
     --filter="config.name=monitoring.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "monitoring.googleapis.com is enabled in vd-shop-dp-stg-0"
else
  note "monitoring.googleapis.com is not enabled in vd-shop-dp-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-dp-stg-0" \
     --filter="config.name=pubsub.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "pubsub.googleapis.com is enabled in vd-shop-dp-stg-0"
else
  note "pubsub.googleapis.com is not enabled in vd-shop-dp-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-dp-stg-0" \
     --filter="config.name=sqladmin.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "sqladmin.googleapis.com is enabled in vd-shop-dp-stg-0"
else
  note "sqladmin.googleapis.com is not enabled in vd-shop-dp-stg-0 yet; this stage enables it on apply"
fi
if gcloud services list --enabled --project="vd-shop-dp-stg-0" \
     --filter="config.name=storage.googleapis.com" --format="value(config.name)" 2>/dev/null | grep -q .; then
  ok "storage.googleapis.com is enabled in vd-shop-dp-stg-0"
else
  note "storage.googleapis.com is not enabled in vd-shop-dp-stg-0 yet; this stage enables it on apply"
fi

printf '\n'
if [ "${fail}" -ne 0 ]; then
  printf 'Preflight failed. Each FAIL above names the assumption and the\n'
  printf 'resource it is about. Fix those before applying %s.\n' "3-app-checkout-stg"
  exit 1
fi
printf 'Preflight passed: every assumption %s makes holds in this environment.\n' "3-app-checkout-stg"
