#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Start the replication inventory-replica-replicate-prd into inventory-replica-relational-prd, after 3-app-inventory-replica-prd is applied.
# Generated by Merlin Studio. Nothing here leaves your environment.
#
#   ./deploy/replicate-inventory-replica-replicate-prd.sh demote --confirm   # once, after the apply
#   ./deploy/replicate-inventory-replica-replicate-prd.sh start              # when the demotion has finished
set -uo pipefail

project="vd-seller-dp-prd-0"
region="europe-west4"
job="inventory-replica-replicate-prd"
instance="inventory-replica-relational-prd"
step="${1:-}"
confirm="${2:-}"

ok()   { printf 'OK   %s\n' "$*"; }
fail() { printf 'FAIL %s\n' "$*"; exit 1; }

case "$step" in
  demote)
    gcloud sql instances describe "$instance" --project="$project" >/dev/null 2>&1 \
      || fail "instance $instance not found in $project; apply 3-app-inventory-replica-prd first"
    extra=$(gcloud sql databases list --instance="$instance" --project="$project" \
      --format="value(name)" 2>/dev/null | grep -vxE 'postgres|cloudsqladmin|template0|template1|mysql|information_schema|performance_schema|sys' || true)
    [ -z "$extra" ] || fail "$instance holds databases of its own ($extra); a replication destination must be empty"
    ok "$instance holds only system databases"
    if [ "$confirm" != "--confirm" ]; then
      printf 'Demoting makes %s a read replica of the source until it is promoted.\n' "$instance"
      printf 'Run again with: demote --confirm\n'
      exit 2
    fi
    gcloud database-migration migration-jobs demote-destination "$job" \
      --region="$region" --project="$project" || fail "demotion of $instance failed"
    ok "demotion requested; run \"start\" once it has finished"
    ;;
  start)
    gcloud database-migration migration-jobs verify "$job" --region="$region" --project="$project" \
      || fail "the job did not verify; the output above names what the service could not reach"
    gcloud database-migration migration-jobs start "$job" --region="$region" --project="$project" \
      || fail "the job did not start"
    ok "$job started"
    printf 'After promoting %s, set %s = false and apply 3-app-inventory-replica-prd: backups and point-in-time recovery come back.\n' "$instance" "inventory_replica_replicate_prd_replicating"
    ;;
  *)
    printf 'usage: %s demote --confirm | start\n' "$0"
    exit 2
    ;;
esac
