#!/usr/bin/env bash
# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# Check this bundle against the landing zone in front of it, before anything
# is applied. Generated by Merlin Studio for Cloud Foundation Fabric v58.0.0.
#
#   ./deploy/verify.sh /path/to/fabric-checkout
#
# Exits non-zero if the landing zone is not the one these workloads were
# compiled against, or if a stage does not validate.
set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAST_DIR="${1:-${FAST_CHECKOUT:-}}"

# shellcheck source=/dev/null
source "${BUNDLE_DIR}/deploy/stages.env"

fail=0
note() { printf '  %s\n' "$*"; }
ok()   { printf 'OK   %s\n' "$*"; }
bad()  { printf 'FAIL %s\n' "$*"; fail=1; }

printf '\nLanding zone\n'
if [ -z "${FAST_DIR}" ]; then
  bad "no Fabric checkout given"
  note "usage: ./deploy/verify.sh /path/to/fabric-checkout"
elif [ ! -d "${FAST_DIR}" ]; then
  bad "no such directory: ${FAST_DIR}"
else
  # The landing zone writes its fingerprint into the manifest it ships. These
  # workloads reference its projects, networks and keys by name, so applying
  # them onto a different landing zone either misses those names or, worse,
  # hits something that happens to share one.
  manifest="$(find "${FAST_DIR}" -name MERLIN_LANDING_ZONE.json -print -quit 2>/dev/null || true)"
  if [ -z "${manifest}" ]; then
    bad "no MERLIN_LANDING_ZONE.json under ${FAST_DIR}"
    note "copy the landing-zone bundle into the checkout before applying workloads"
  else
    deployed="$(sed -n 's/.*"spec_fingerprint"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "${manifest}" | head -1)"
    if [ -z "${MERLIN_LANDING_ZONE_FINGERPRINT}" ] || [ -z "${deployed}" ]; then
      # Skipping this is how a workload bundle gets applied onto a landing
      # zone it was never compiled against, and the names it references
      # happen to exist.
      bad "the landing zone cannot be identified"
      note "workloads compiled against: ${MERLIN_LANDING_ZONE_FINGERPRINT:-<none recorded>}"
      note "landing zone in checkout:   ${deployed:-<none recorded>}"
      note "regenerate the landing zone, then the workloads, so both carry one"
    elif [ "${deployed}" = "${MERLIN_LANDING_ZONE_FINGERPRINT}" ]; then
      ok "landing zone matches the one these workloads were compiled against"
    else
      bad "landing zone does not match"
      note "compiled against: ${MERLIN_LANDING_ZONE_FINGERPRINT}"
      note "found in checkout: ${deployed:-<none>}"
      note "regenerate the workloads from the landing zone you actually deployed"
    fi
  fi
fi

printf '\nStages\n'
while IFS='|' read -r stage kind environment dataset identity; do
  [ -n "${stage}" ] || continue
  if [ ! -d "${BUNDLE_DIR}/${stage}" ]; then
    bad "${stage}: missing from the bundle"
    continue
  fi
  ok "${stage} (${kind}${environment:+, ${environment}}) deploys as ${identity}"
done <<< "${MERLIN_STAGES}"

printf '\nTerraform\n'
if ! command -v terraform >/dev/null 2>&1; then
  note "terraform is not on PATH; skipping fmt and validate"
else
  while IFS='|' read -r stage kind environment dataset identity; do
    [ -n "${stage}" ] || continue
    [ "${kind}" = "root" ] || continue          # a dataset is YAML, not a root
    if terraform fmt -check -recursive "${BUNDLE_DIR}/${stage}" >/dev/null 2>&1; then
      ok "${stage} is formatted"
    else
      bad "${stage} is not formatted (terraform fmt)"
    fi
  done <<< "${MERLIN_STAGES}"
  note "run apply.sh --plan-only for a full validate against the checkout's modules"
fi

printf '\n'
if [ "${fail}" -ne 0 ]; then
  printf 'verify failed; nothing was applied\n'
  exit 1
fi
printf 'verify passed\n'
